- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .gitignore
- README.md
- integration/SimpleCacheClient.test.ts
- package-lock.json
- package.json
- src/Momento.ts
- src/MomentoCache.ts
- src/messages/ListCachesResponse.ts
- src/messages/Result.ts
- test/messages/Result.test.ts
Updated `@grpc/grpc-js` version to the latest so that the issue of the integration tests failure on GitHub Action mentioned in https://github.com/momentohq/client-sdk-javascript/issues/49 will be mitigated.
Closes #49
> chore: Update `@grpc/grpc-js` version to the latest 

- integration/SimpleCacheClient.test.ts
- src/CacheServiceErrorMapper.ts
- src/Errors.ts
> chore: Add cause traceback to internal server exceptions

- src/Momento.ts
- src/MomentoCache.ts
- tsconfig.json
> chore: Add `agent` metadata

- src/Momento.ts
- src/MomentoCache.ts
- src/grpc/HeadersInterceptor.ts
Following [this csharp sdk pattern](https://github.com/momentohq/client-sdk-csharp/pull/38) to be future proof for any additional metadata in the future.
> chore: Create new `Header` class

- integration/SimpleCacheClient.test.ts
- package-lock.json
- package.json
- src/Momento.ts
- src/MomentoCache.ts
- src/SimpleCacheClient.ts
- src/messages/CreateSigningKeyResponse.ts
- src/messages/ListSigningKeysResponse.ts
- src/messages/RevokeSigningKeyResponse.ts
- src/messages/SigningKey.ts
Adds support for `CreateSigningKey`, `RevokeSigningKey`, and `ListSigningKeys`
> feat: add support for signing keys APIs

- src/SimpleCacheClient.ts
> chore: Update end-user facing documentation.

- package-lock.json
- package.json
- src/index.ts
- src/utils/logging.ts
Console format is pretty-printed in a fashion that is a little
more human-readable for developers.
> feat: support configuring log format as JSON vs CONSOLE

- .github/workflows/build.yml
- .github/workflows/on-push-to-main-branch.yml
- README.template.md
@cprice404 Opened a pr in the `standards-and-practices` repo: https://github.com/momentohq/standards-and-practices/pull/26 to update `action.yml` 
I'd like to merge that pr first and merge this pr in the `client-sdk-javascript`
> chore: test oss-readme-template GH action

- package-lock.json
- package.json
Fix for dependabot security alert. Will need another PR after this to fix `examples` project in here after this is released.
> fix: vuln in JOSE lib

- examples/load-gen.ts
* Don't pull BasicJavaScriptLoadGenOptions apart into individual attributes; this makes it easier to add options.
* Make delayMillisBetweenRequests a BasicJavascriptLoadGen attribute so we don't have to pass it through.
* Don't pass through individual options.
> refactor: Reduce pass-through args in BasicJavascriptLoadGen

- src/utils/collection-ttl.ts
- test/utils/collection-ttl.test.ts
Here is the promised CollectionTtl. I'm hoping to get it merged so we can all start using it.
The docs are copied from dotnet and have not yet been converted.
> feat: CollectionTtl to pass to collection methods.

- integration/simple-cache-client.test.ts
- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-get.ts
- src/messages/responses/cache-list-fetch.ts
- src/messages/responses/cache-list-push-front.ts
- src/simple-cache-client.ts
- src/utils/display.ts
- src/utils/validators.ts
- test/cache-get.test.ts
- test/cache-list-fetch.test.ts
- test/cache-list-push-front.test.ts
This adds two list data structures, enough to establish a pattern and test them.
- ListFetch
- ListPushFront
Also:
- Make `CacheGet.Hit.toString()` consistent when the value is truncated.
> feat: Add ListFetch and ListPushFront

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-set-add-elements.ts
- src/messages/responses/cache-set-fetch.ts
- src/messages/responses/cache-set-remove-elements.ts
- src/simple-cache-client.ts
There is a few small TODOs left that can be fast-followed after this
PR is merged.
Integ tests are not added yet, that will be done in the next PR.
> feat: basic implementation of SetAddElements and SetRemoveElements

- integration/simple-cache-client.test.ts
- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-set-add-elements.ts
- src/messages/responses/cache-set-fetch.ts
- src/messages/responses/cache-set-remove-elements.ts
- src/simple-cache-client.ts
- test/cache-set-fetch.test.ts
you probably want to review/approve this guy first: https://github.com/momentohq/client-sdk-javascript/pull/171
> feat: add unit and integ tests for sets operations

- src/internal/cache-client.ts
- src/simple-cache-client.ts
A few small fixes I noticed.
* ListPushFront was using ListFetch types.
* Use convertArray() everywhere to map arrays to bytes.
> fix: Small fixes to data structures.

- src/index.ts
- src/internal/cache-client.ts
- src/internal/control-client.ts
- src/simple-cache-client.ts
A quality of life refactor.
* UnknownError was not being exported. Seems it should be available to the user.
> refactor: Reduce the number of places we need to add a response import.

- examples/README.md
- examples/dictionary.ts
- examples/index.ts
- examples/load-gen.ts
- examples/package-lock.json
- examples/package.json
- examples/presigned-url-example.ts
Add an example for the dictionary data type. It mirrors the functionality of the example in the c# sdk.
Update the examples to work with the latest sdk release.
> chore: add dictionary examples

- src/index.ts
Export StringMomentoTokenProvider to allow customers to use it.
> chore: export the string auth token provider

- src/config/logging/default-momento-logger.ts
- src/index.ts
Add Momento the log messages to make it easier to pick our log messages out.
> chore: add Momento to the log messages

- src/internal/control-client.ts
- src/simple-cache-client.ts
Remove the page token from the list signing keys method. It is not implemented and paging can be encapsulated in the sdk in the future.
> chore: remove the list signing keys page token

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-sorted-set-get-rank.ts
- src/simple-cache-client.ts
This commit wires up the request/response logic for sortedSetGetRank. No tests yet because I didn't want to cause merge conflicts in the test file.
> feat: adds sortedSetGetRank function

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-sorted-set-increment-score.ts
- src/simple-cache-client.ts
This commit wires up the request/response logic for sortedSetIncrementScore. No tests yet because I didn't want to cause merge conflicts in the test file.
> feat: adds sortedSetIncrementScore function

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-sorted-set-get-score.ts
- src/simple-cache-client.ts
- src/utils/cache-call-options.ts
Implement `sortedSetGetScore`. In a future PR we will implement `sortedSetGetScores` and also write tests.
> feat: sorted set get score

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-sorted-set-remove-element.ts
- src/messages/responses/cache-sorted-set-remove-elements.ts
- src/simple-cache-client.ts
No tests yet, will add once the test pattern stabilizes.
> feat: add sortedSetRemoveElements

- src/index.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-sorted-set-get-score.ts
- src/messages/responses/cache-sorted-set-get-scores.ts
- src/simple-cache-client.ts
Implements `sortedSetGetScores` and refactors `sortedSetGetScore` to
delegate to the former.
> feat: implement `sortedSetGetScores`

- examples/request-coalescing.ts
- examples/utils/load-gen-statistics-calculator.ts
- Remove unused imports from utils
> fix: remove unused imports

- src/internal/pubsub-client.ts
- src/internal/utils/validators.ts
- src/messages/responses/topic-subscribe.ts
- test/integration/integration-setup.ts
- test/integration/topic-client.test.ts
Implements a test suite for the topic client.
Work toward #343
> test: topic client test suite

- examples/README.md
- examples/advanced.ts
- examples/basic.ts
- examples/package-lock.json
- examples/package.json
- examples/topic-publish.ts
- examples/topic-subscribe.ts
- examples/utils/cache.ts
Add a basic pubsub example and documentation.
> feat: pubsub examples

- examples/README.md
Add stats and steps to run the request-coalescing example. 
https://github.com/momentohq/dev-eco-issue-tracker/issues/204
> feat: Add prompt for request-coalescer example

- examples/README.md
- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/common/src/auth/credential-provider.ts
- packages/common/src/internal/utils/auth.ts
- packages/common/test/unit/auth/credential-provider.test.ts
- packages/common/test/unit/utils/auth.test.ts
This PR is the first of two intended to get us back into sync with the `main` branch.  This contains cherry-picks of all of the commits to main except the most recent one (which updates how we handle the index.ts file).
There will be one more PR to reconcile the indices between `main` and the feature branch.
> chore: merge recent changes from main (1/2)

- scripts/publish-all-packages.sh
- scripts/publish-package.sh
- scripts/wait-for-npmjs-release.sh
This commit updates the publish scripts to publish the node.js
SDK package in addition to the core package.  We add a script
to wait for the core package to be available on node.js, then
update the dependency in the nodejs SDK package to use the newly
released version of core, then publish the nodejs package.
> feat: publish the node.js client library from the new package structure

- packages/core/src/internal/utils/string.ts
Forgot to remove before merging https://github.com/momentohq/client-sdk-nodejs/pull/489
> chore: remove comment about deprecated method

- packages/client-sdk-nodejs/src/index.ts
- chore: add missing expireIn/At
> chore: missing export expires in/at

- .github/workflows/on-push-to-release-branch.yml
This is an attempt to fix the issue where our README is not showing
up on npm.js.
> fix: copy README to nodejs dir so that it will be included in the npm package

- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
Fix docs for ItemGetTypeResponse
> fix: docs for ItemGetTypeResponse

- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/topic-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/topic-client.ts
- packages/client-sdk-web/src/utils/web-client-utils.ts
- packages/core/src/internal/clients/pubsub/AbstractPubsubClient.ts
- packages/core/src/internal/clients/pubsub/AbstractTopicClient.ts
This commit refactors shared logic from the nodejs and web pubsub/topic clients into abstract base classes.  It also extracts a couple utility functions used in the web sdk into their own utils package.
> chore: DRY out clients

- examples/nodejs/doc-examples-js-apis.ts
`
SDK 'javascript' is missing 53 snippets and 0 files.
Missing snippets: API_ConfigurationLambda,API_DictionaryFetch,API_DictionaryGetField,API_DictionaryGetFields,API_DictionaryIncrement,API_DictionaryRemoveField,API_DictionaryRemoveFields,API_DictionarySetField,API_DictionarySetFields,API_DictionaryLength,API_SetAddElement,API_SetAddElements,API_SetFetch,API_SetRemoveElement,API_SetRemoveElements,API_SetContainsElement,API_SetContainsElements,API_SetLength,API_TopicSubscribe,API_TopicPublish,API_InstantiateTopicClient,API_Increment,API_Ping,API_ItemGetType,API_KeyExists,API_KeysExist,API_SetIfNotExists,API_UpdateTtl,API_IncreaseTtl,API_DecreaseTtl,API_ItemGetTtl,API_ListFetch,API_ListConcatenateBack,API_ListConcatenateFront,API_ListLengt …
> feat: add increment, itemGetType, SetIfNotExists API examples for docs

- packages/client-sdk-web/test/integration/integration-setup.ts
use correct config when creating topic client
> fix: use correct config when creating topic client

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
Remove idle grpc wrapper client
Integration tests : `npm run build-and-run-tests`
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/380
> feat: remove idle grpc wrapper client

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
- Add code examples of generating tokens with different permissions for GenerateAuthToken docs
-  ~Builds will fail on the PR workflow jobs because the SDK changes are not yet merged/released but I have run these locally.~ Fixed by updating sdk version after new momento sdk was released
```
> momento-nodejs-example@1.0.0 doc-examples
> tsc && node dist/doc-example-files/doc-examples-js-apis.js
[2023-07-11T01:00:29.152Z] INFO (Momento: CacheClient): Creating Momento CacheClient
[2023-07-11T01:00:29.170Z] INFO (Momento: CacheClient): Creating Momento CacheClient
[2023-07-11T01:00:29.171Z] INFO (Momento: ControlClient): Creating cache: test-cache
Cache 'test-cache' created
Key 'test-key' was not found in cache 'test-cache'
Key 'test-key' stored successfully
[2023-07-11T01:00:29.686Z] INFO …
```
> feat: Add example code snippets for fine grained access control tokens

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-nodejs/test/integration/shared/update-ttl.test.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/client-sdk-web/test/integration/shared/update-ttl.test.ts
- packages/common-integration-tests/src/index.ts
- packages/common-integration-tests/src/update-ttl.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/messages/responses/cache-ttl-decrease.ts
- packages/core/src/messages/responses/cache-ttl-increase.ts
- packages/core/src/messages/responses/cache-ttl-update.ts
Addresses #614 by adding the update/increase/decrease TTL APIs to the JS SDK
> feat: update/increase/decrease ttl

- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
Session tokens are complicated to acquire, and the tests that require
them are not relevant for most dev work on this package. Prior to this
commit we were eagerly constructing CredentialProviders that used
session tokens on every run of the integration test suite, regardless
of whether we would actually be executing the related tests or not.
This commit changes the instantiation of the session token CredProvider
to be lazy, so that it is not necessary to provide the session token
env var on test runs that do not exercise it.
> fix: lazily instantiate session token cred provider during tests

- examples/web/README.md
- examples/web/nextjs-chat/README.md
- examples/web/vite-chat-app/README.md
Addresses [#393](https://github.com/momentohq/dev-eco-issue-tracker/issues/393) by fleshing out the READMEs associated with the Vite and Next.js chat examples.
> chore: update chat app example readmes

- examples/nodejs/token-vending-machine/README.md
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/config.ts
- examples/web/vite-chat-app/.env.development
- examples/web/vite-chat-app/README.md
- examples/web/vite-chat-app/package-lock.json
- examples/web/vite-chat-app/package.json
- examples/web/vite-chat-app/src/utils/momento-web.ts
Follow up to #677 to show how the Vite app can be configured to use the token vending machine with any of the auth options (no auth, lambda authorizer, or cognito user pool).
> feat: vite chat app with authenticated token vending machine

- packages/client-sdk-nodejs/src/cache-client-props.ts
- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-nodejs/test/unit/cache-client.test.ts
Add a factory method that creates a CacheClient and attempts to eagerly establish all of its data client connections.
> feat: Add eager connction client factory method.

- packages/client-sdk-nodejs/src/topic-client.ts
- packages/client-sdk-web/src/topic-client.ts
This commit corrects a log message that caused me great confusion.
> fix: correct log messages when instantiating TopicClient

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/common-integration-tests/src/dictionary.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/messages/responses/cache-dictionary-length.ts
- Add dictionary length api to nodejs and web-sdk
- Add integ tests
> feat: add dictionary length api

- examples/nodejs/load-gen/load-gen.ts
- examples/nodejs/load-gen/request-coalescing.ts
For https://github.com/momentohq/dev-eco-issue-tracker/issues/431
> chore: update load-gen comments to be more clear on maxConn behavior

- .github/workflows/build.yml
> fix: dependabot auto merge

- .github/workflows/build.yml
> fix: dependabot auto merge should squash merge

- .github/dependabot.yml
https://github.com/momentohq/client-sdk-javascript/pull/778/files dependabot was not updating all example directories
> fix: Update dependabot.yml to include _all_ example dirs

- examples/cloudflare-workers/http-api/README.md
- examples/cloudflare-workers/http-api/src/worker.ts
- examples/cloudflare-workers/web-sdk/README.md
- examples/cloudflare-workers/web-sdk/src/worker.ts
Closes https://github.com/momentohq/client-sdk-javascript/issues/834
> chore: update cloudflare README to be more explicit about uncommenting lines

- .gitignore
- examples/nodejs/cache/README.md
- examples/nodejs/cache/leaderboard.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-client.ts
- packages/client-sdk-nodejs/src/leaderboard-client.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/leaderboard-client.ts
- packages/client-sdk-web/src/leaderboard-client.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/leaderboard/AbstractLeaderboardClient.ts
- packages/core/src/messages/responses/leaderboard/leaderboard-fetch.ts
- packages/core/src/messages/responses/leaderboard/leaderboard-get-rank.ts
- packages/core/src/messages/responses/leaderboard/leaderboard-length.ts
Follow up to #949 and addresses [#468](https://github.com/momentohq/dev-eco-issue-tracker/issues/468).
Realized I had set up the extends/implements structures incorrectly so I fixed that.
Also created the tarballs and wrote an example that uses the version installed in them.
> fix: fixed plumbing of clients and added example

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-control-client.ts
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-control-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/vector-control-plane.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/clients/IVectorIndexClient.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/vector/AbstractVectorIndexClient.ts
- packages/core/src/internal/clients/vector/IVectorIndexControlClient.ts
- packages/core/src/internal/clients/vector/IVectorIndexDataClient.ts
- packages/core/src/messages/responses/vector/index.ts
- packages/core/src/messages/responses/vector/vector-upsert-item-batch.ts
Rename addItemBatch to upsertItemBatch to reflect its new upsert functionality.
Make metadataFields in SearchOptions either an array of metadata fields, or a sentinel value representing all metadata.
Add a similarity metric enum to createIndex to let the user specify which metric to use when creating an index.
> feat: MVI method updates

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
Update node and web doc examples.
> chore: update doc examples

- .github/workflows/build.yml
- examples/nodejs/vector-index/.eslintignore
- examples/nodejs/vector-index/.eslintrc.json
- examples/nodejs/vector-index/.prettierrc.json
- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/nodejs/vector-index/tsconfig.json
Run the vector index doc examples as a part of the build.
Add a vector index client instantiation example.
> chore: run vector index doc examples

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/leaderboard.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
Addresses [#468](https://github.com/momentohq/dev-eco-issue-tracker/issues/468) and a follow up to #966. Updates examples to match latest batch of leaderboard SDK changes.
> chore: update leaderboard examples following bug bash fixes

- examples/cloudflare-workers/web-sdk/wrangler.toml
Preserve environment variables added via UI when doing a deploy. Follow up to https://github.com/momentohq/client-sdk-javascript/pull/946
> chore: preserve environment variables on cflare deployments

- CONTRIBUTING.md
Tweak contributing docs: `s/auth token/api key/`
> docs: tweak docs to trigger release

- examples/web/nextjs-chat/package-lock.json
- examples/web/nextjs-chat/package.json
- examples/web/nextjs-chat/src/app/api/momento/token/route.ts
- examples/web/nextjs-chat/src/app/page.tsx
- examples/web/nextjs-chat/src/app/pages/chat-room.tsx
- examples/web/nextjs-chat/src/utils/momento-web.ts
Instead of passing a user's name involve in chat through a topic message, we are inferring it through the `tokenId` in `TopicItem`. This will be demonstrated in a blog where we can say that users can save $$ going forward by following this route.
The username is being passed around through a query string.
> chore: use username as tokenId for nextjs chat examples

- packages/client-sdk-web/src/index.ts
- Add more imports/exports from web-sdk to be able to consume in console
> fix: add more imports/exports from web-sdk

- packages/client-sdk-nodejs/test/integration/integration-setup.ts
[Release failed](https://github.com/momentohq/client-sdk-javascript/actions/runs/6737933679/job/18316441495) because of this lint error
> fix: lint error

- examples/nodejs/rate-limiter/doc-examples-files/doc-examples.ts
Doc snippet for rate-limiter plugged here and tested locally it works https://github.com/momentohq/public-dev-docs/pull/505
> chore: add doc snippet forr rate-limter

- CONTRIBUTING.md
Update documentation to trigger a release.
> docs: minor tweak

- examples/nodejs/observability/doc-example-files/doc-examples-js-apis.ts
Will be used to update the nodejs observability docs to show how people can create momento loggers with different logging levels: https://github.com/momentohq/public-dev-docs/pull/510
> chore: add momento logger example

- CONTRIBUTING.md
Tweak documentation in order to release again.
> chore: tweak documentation

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
Update MVI examples in Node.js and web for `getItemBatch` and `getItemMetadataBatch`.
> chore: update mvi example snippets

- package-lock.json
- packages/client-sdk-web/src/config/topic-configurations.ts
- Add laptop & browser config to topics in web-sdk 
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/603
> feat: add laptop & browser config to topics in web-sdk

- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
Prior to this commit, the node.js leaderboard client did not honor the
our grpc config setting for "numClients", which is intended to control the
number of TCP connections we make to the server. This commit adds support
for that setting, meaning that users who may exceed 100 concurrent requests
can increase the value in order to get higher throughput.
> feat: support configuring multiple grpc connections for leaderboard client

- examples/nodejs/cache/package.json
- examples/nodejs/cache/sharded-dictionary.ts
An example of a sharded dictionary, which can be used to store more data than would fit in an individual collection. This came up in a conversation with a user who was interested in storing more than 5mb in a single dictionary.
> chore: example of an abstraction to create a sharded dictionary

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/test/unit/cache-client.test.ts
- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/dictionary.ts
- packages/common-integration-tests/src/get-set-delete.ts
- packages/common-integration-tests/src/list.ts
- packages/core/src/internal/utils/validators.ts
- packages/core/src/utils/collection-ttl.ts
- packages/core/test/unit/utils/collection-ttl.test.ts
addresses https://github.com/momentohq/client-sdk-javascript/issues/1147
> fix: ttl validator should check for positive integers

- packages/client-sdk-nodejs/test/integration/large-messages.test.ts
- packages/common-integration-tests/src/create-delete-list-cache.ts
Sets and gets a string with 5million bytes (~5mb)
> chore: make sure nodejs can set and get 5mb messages

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
Adds missing doc snippets for getBatch and setBatch to be used in https://github.com/momentohq/public-dev-docs/pull/758
> chore: add code snippets for getBatch and setBatch

- examples/nodejs/cache/advanced.ts
- examples/nodejs/cache/package.json
Just figured the advanced example could benefit with an update with the factory method for middleware construction and also closing the client.
> chore: update advanced example to use middleware factory

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
https://github.com/momentohq/dev-eco-issue-tracker/issues/637
> chore: bump grpc js

- .github/workflows/build.yml
- .github/workflows/on-push-to-main-branch.yml
- .github/workflows/on-push-to-release-branch.yml
- CONTRIBUTING.md
- packages/client-sdk-nodejs-compression/test/integration/integration-setup.ts
- packages/client-sdk-nodejs/test/integration/client-constructor-default-configs.test.ts
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-nodejs/test/unit/cache-client.test.ts
- packages/client-sdk-web/test/integration/client-constructor-default-configs.test.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/internal/ping.test.ts
- packages/core/test/unit/auth/credential-provider.test.ts
- s/TEST_AUTH_TOKEN/TEST_API_KEY
> chore: rename TEST_AUTH_TOKEN to TEST_API_KEY

- packages/client-sdk-nodejs-compression/test/integration/compression.test.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/utils/cache-call-options.ts
Adds compression support and integration tests for `setIfAbsent`.
> feat: add compression support for setIfAbsent

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/785
> chore: reinstate get and set batch docs examples

- examples/nodejs/get-set-batch-perf-test/perf-test.ts
Use the new CacheGetBatch and CacheSetBatch response types in the example code
> fix: update SetBatch and GetBatch response types

- examples/nodejs/cache/advanced.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/core/src/messages/responses/cache-batch-get.ts
- packages/core/src/messages/responses/cache-batch-set.ts
- packages/core/src/messages/responses/cache-delete.ts
- packages/core/src/messages/responses/cache-increment.ts
- packages/core/src/messages/responses/cache-set-if-absent-or-equal.ts
- packages/core/src/messages/responses/cache-set-if-absent.ts
- packages/core/src/messages/responses/cache-set-if-equal.ts
- packages/core/src/messages/responses/cache-set-if-not-equal.ts
- packages/core/src/messages/responses/cache-set-if-not-exists.ts
- packages/core/src/messages/responses/cache-set-if-present-and-not-equal.ts
- packages/core/src/messages/responses/cache-set-if-present.ts
- packages/core/src/messages/responses/enums/cache/scalar/index.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/844
> feat: migrate scalar responses to new enum pattern

- packages/common-integration-tests/src/list.ts
- packages/core/src/messages/responses/cache-list-concatenate-back.ts
- packages/core/src/messages/responses/cache-list-concatenate-front.ts
- packages/core/src/messages/responses/cache-list-fetch.ts
- packages/core/src/messages/responses/cache-list-length.ts
- packages/core/src/messages/responses/cache-list-pop-back.ts
- packages/core/src/messages/responses/cache-list-pop-front.ts
- packages/core/src/messages/responses/cache-list-push-back.ts
- packages/core/src/messages/responses/cache-list-push-front.ts
- packages/core/src/messages/responses/cache-list-remove-value.ts
- packages/core/src/messages/responses/cache-list-retain.ts
- packages/core/src/messages/responses/enums/cache/index.ts
- packages/core/src/messages/responses/enums/cache/list/index.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/846
> feat: migrate list responses to new enum pattern

- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/grpc/headers-interceptor.ts
- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/internal/ping-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/internal/webhook-client.ts
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/client-sdk-web/src/internal/cache-control-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/client-metadata-provider.ts
- packages/client-sdk-web/src/internal/leaderboard-data-client.ts
- packages/client-sdk-web/src/internal/ping-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/internal/webhook-client.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/888
All the clients that send headers:
- cache
- topic
- leaderboard
- webhook
- auth
- ping
> feat: make sure Agent and Runtime-Version headers are sent once

- examples/nodejs/token-vending-machine/README.template.md
Closes https://github.com/momentohq/client-sdk-javascript/issues/1398
Adds note to log out of Amazon public ECR if running into errors deploying
> chore: update token vending machine readme

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- packages/common-integration-tests/src/webhooks.ts
- packages/core/src/messages/responses/enums/index.ts
- packages/core/src/messages/responses/enums/webhook/index.ts
- packages/core/src/messages/responses/webhook/delete-webhook.ts
- packages/core/src/messages/responses/webhook/get-webhook-secret.ts
- packages/core/src/messages/responses/webhook/list-webhooks.ts
- packages/core/src/messages/responses/webhook/put-webhook.ts
- packages/core/src/messages/responses/webhook/rotate-webhook-secret.ts
I had to comment out the example code for webhooks since the CI kept failing for it. 
Will publish this sdk version and update the tests accordingly in a follow-up pr.
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/956
> feat: Port webhooks api to new switch pattern

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
- packages/common-integration-tests/src/webhooks.ts
- upgrade to latest sdk version in examples
- update relevant webhook examples
https://github.com/momentohq/dev-eco-issue-tracker/issues/956
> feat: update webhook examples to new switch pattern

- examples/nodejs/storage/advanced.ts
- examples/nodejs/storage/package.json
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/878
> chore: add storage retry strategy override example

- packages/client-sdk-nodejs/test/unit/config/retry/default-eligibility-strategy.test.ts
- Modify and add unit tests for default retry eligibility.
https://github.com/momentohq/dev-eco-issue-tracker/issues/1094
> chore: add and modify retry default eligibility unit tests

- packages/client-sdk-nodejs/test/integration/retry/automated-retry-tests.test.ts
Follow-up PR for https://github.com/momentohq/client-sdk-javascript/pull/1510
> chore: add more assertions to retry-tests

- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- Add grpc channel options for control client
https://gomomento.slack.com/archives/C037XLHFC79/p1740699484909389
related pr investigation: https://github.com/momentohq/client-sdk-javascript/pull/1523
> feat: add grpc channel options to cache control client

- examples/nodejs/aws/lambda-examples/advanced-compression/src/index.ts
- scripts/update-all-examples-dependencies.sh
- Modify the example script to ensure it always installs the latest version of the compression libraries. The latest versions weren't being picked up previously, likely due to caching or versioning issues.
- Update the advanced-compression example to resolve an issue where the `CompressorFactory` in the `compression-zstd` library does not have a `default()` function. Instead, the correct function to use is `zstd()`.
> fix: update the example script to always install the latest version of the sdk/(extensions)

- .github/workflows/build.yml
I missed a reference to a deleted test in CI in #1561
> chore: remove a reference to a removed test I missed earlier

- packages/common-integration-tests/src/auth/auth-client.ts
Recent canary failures were caused by `RESOURCE_EXHAUSTED: Your account has a limit of 10 caches` errors.
We suspect that the auth tests somehow leaked caches created by the session token client account over time (unsure of the time frame though).
This PR adds a couple of `deleteCache` calls to prevent leaked caches and renames the caches to be easily recognizable if this error occurs again on the session token client account.
> chore: make sure auth tests don't leak caches

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
I added a code snippet for sortedSetUnionStore..
> chore: added sortedSetUnionStore example
