momentohq/client-sdk-javascript

- integration/SimpleCacheClient.test.ts
Based on our conversations [here](https://gomomento.slack.com/archives/C037XLHFC79/p1648677574935629).
> fix: Update integration tests to delete existing cache before creating one

- integration/SimpleCacheClient.test.ts
- package-lock.json
- package.json
- src/MomentoCache.ts
- src/SimpleCacheClient.ts
- src/messages/DeleteResponse.ts
This should not get merged until https://github.com/momentohq/cacheservice/pull/654 gets merged and deployed
> feat: add support for deleting keys

- .github/workflows/cd.yml
We currently read our package.json file in programmatically to obtain sdk version. This commit copies down package.json into dist folder during publish so code can access it in a consistent way.
Loosely following advice off [this](https://stackoverflow.com/questions/38858718/npm-script-copy-package-json-to-dist-when-bundling) SO post. Feels like there should be cleaner way to do this like we do in python for example with `pkg_resources.get_distribution("momento").version` but javascript ecosystem does not seem to have a very consistent strategy for doing this.
> fix: copy down package.json into dist during publish

- .github/workflows/cd.yml
- package.json
- tsconfig.json
Still having issues with package json after last fix. Was able to verify this locally w/ 
```
npm run build
npm pack
```
I believe it should work on publish now and copy step added previously might not actually be needed.
```
✗ npm pack
npm notice
npm notice 📦  @gomomento/sdk@0.0.1
npm notice === Tarball Contents ===
npm notice 11.4kB LICENSE
npm notice 1.9kB  README.md
npm notice 1.6kB  dist/package.json   ## <--- Can see now!!!
npm notice 186B   dist/src/CacheServiceErrorMapper.d.ts
npm notice 6.7kB  dist/src/CacheServiceErrorMapper.js
npm notice 3.0kB  dist/src/Errors.d.ts
npm notice 13.1kB dist/src/Errors.js
...
```
> fix: try different way including package.json in published bundle

- package-lock.json
Fixes [[CVE-2022-25878]](https://github.com/advisories/GHSA-g954-5hwp-pp24)
`npm audit` output prior to fix
```
$ npm audit
protobufjs  6.11.0 - 6.11.2
Severity: high
Prototype Pollution in protobufjs - https://github.com/advisories/GHSA-g954-5hwp-pp24
fix available via `npm audit fix`
node_modules/protobufjs
1 high severity vulnerability
To address all issues, run:
npm audit fix
```
`npm audit` output after fix
```
$ npm audit
found 0 vulnerabilities
```
> fix: [CVE-2022-25878] - Prototype Pollution in protobufjs

- integration/SimpleCacheClient.test.ts
- package-lock.json
- package.json
- src/Momento.ts
- src/MomentoCache.ts
- src/SimpleCacheClient.ts
- src/index.ts
- src/utils/logging.ts
- test/SimpleCacheClient.test.ts
This commit adds a quick-and-dirty first cut of supporting
logging and logging configuration.  I chose to use the 'pino'
logging framework for now, because it is one of the more popular
JS frameworks, supports nodejs and browser, and seems to be
focused on performance.
We abstract the logging implementation behind our own facade so
that we can swap out pino later for a different library if
we decide we need to, without making any breaking changes to
our API.
> feat: add minimal logging capabilities

- package-lock.json
- package.json
- src/Momento.ts
- src/MomentoCache.ts
- src/SimpleCacheClient.ts
- src/grpc/RetryInterceptor.ts
- src/index.ts
- src/utils/logging.ts
This commit fixes a memory issue that surfaced on the retry logic
under higher load.
It also adds a broader array of log levels for users to choose
from, and moves the noisiest log messages to `trace`.  In addition,
there are some places where we had been logging the cache value;
those are removed because for large cache values the log messages
were overwhelming.
> fix: memory issues for retries; improvements to logging

- .github/workflows/push-to-release-branch.yml
This commit changes the behavior so that we won't do a release to
npmjs on every commit to `main`.  We will be releasing from the
`release` branch from now on.  In a future commit we'll add
a manually-dispatched action to trigger a release, which will
involve doing a merge from `main` to `release` and then pushing
to `release` to trigger this action.
For more info see: https://www.notion.so/momentohq/Dev-Eco-Releases-Best-Practices-d3e94013e9d94d9baf255a1173cd1f36
> chore: modify github action to do releases from 'release' branch

- .github/workflows/on-push-to-release-branch.yml
The semver plugin that we are using appears to try to enforce that
the releases only be done from the default branch.  This commit
attempts to disable that check.  Filed this issue to see if they
might support configuring an allowed branch to do releases from:
https://github.com/go-semantic-release/action/issues/25
> fix: attempt to work around semver plugin's branch restriction

- .github/workflows/manual-release.yml
This commit adds a manual workflow to start the release process.
The workflow does a merge from the `main` branch to the `release`
branch, which will then trigger the release via the push to the
`release` branch.
> chore: add a workflow for triggering manual release

- package.json
- src/momento-cache.ts
This commit is modeled after the way the python code is set up.
Instead of passing the cache name as a constructor arg to the
HeaderInterceptor (which forces us to construct a new instance
of that interceptor for each request), we now specify a metadata
object directly on the request that we construct and we set
the cache name there.  This simplifies some of the code because
now we can construct the list of interceptors once at initialization.
> fix: simplify interceptors, pass cache name as metadata

- package-lock.json
- package.json
- src/index.ts
- src/momento-signer.ts
Add new class for creating presigned URLs and user signed access tokens, using signing keys registered with the service via `CreateSigningKey`.
Pulls in the node module `jose` ([github](github.com/panva/jose)/[npm](https://www.npmjs.com/package/jose)) for handling importing JWKs and signing JWTs. This library is linked from the [openID docs](https://openid.net/developers/jwt/) and has 2 million weekly downloads. It's MIT licensed and appears to be active. It seems to support both Browsers and Node. It is somewhat large but doesn't have any dependencies, from the [docs](https://github.com/panva/jose#bundle-size-package-size-tree-shaking):
> Yes the bundle size is on the larger side, that is because each module is actually published multiple times so that it can remain truly without …
> feat: Add MomentoSigner class

- .github/workflows/codeql.yml
Want to give githubs `codeql` tool a try to see if it can catch anything and also will make our public repos look a bit more legit I think. I already enabled on dev docs repo to try it out and looked pretty good. Wanted to start with this SDK see how things went. If looks good here will work to roll out to our other repos over time.
> chore: adds code scanning workflow

- examples/load-gen.ts
- src/momento-cache.ts
Fixes seeing debug logs like this every time.
```bash
{"level":20,"time":1668709906140,"pid":78770,"name":"MomentoCache","msg":"Creating cache client using endpoint: 'cache.cell-ap-northeast-1-1.prod.a.momentohq.com'"}
{"level":20,"time":1668709906154,"pid":78770,"name":"MomentoCache","msg":"Request timeout: undefined"}
```
Also lowers concurrency since we made limits more aggressive for GA launch and ups timeout to be more inline for what we are defaulting in SDK.
> fix: bug in debug logging

- package-lock.json
- src/grpc/grpc-client-wrapper.ts
- src/grpc/idle-grpc-client-wrapper.ts
- src/momento-cache.ts
- src/momento.ts
In some environments such as AWS Lambda, it is possible for
a cache client to be instantiated and stored in a long-lived
(global) variable, which then may not be accessed for long
periods of time (e.g. between lambda invocations).
The lambda environment may suspend the runtime in such a way
that no code will be executing between invocations (i.e., no
keepalive pings).  If there are more than 5 minutes between
lambda invocations, then the server side of the cache client
(AWS NLB) will detect the connection as idle and close it.
On the next lambda invocation, the grpc-js library does not
recognize that the connection has been closed so it will
continue to try to send data to it, resulting in a client-side
timeout (DEADLINE_EXCEEDED).
In this commit we add a wrapper around the client that …
> fix: Introduce idle wrapper around gRPC clients

- package-lock.json
- package.json
We have encountered some minor issues with grpc-js running in
AWS Lambda environment.  We're a little out of date on our
grpc dependency so this brings us up to the latest.  This
didn't fix the AWS lambda issues, but does include some bug
fixes and updates that seem worth picking up.  See release notes
here:
https://github.com/grpc/grpc-node/releases
> chore: update grpc-js library to latest

- .editorconfig
- examples/load-gen.ts
Makes whitespace handling consistent. Honored by many editors, others have a plugin. See https://editorconfig.org/
> chore: Add an editorconfig

- examples/load-gen.ts
* maxRequestsPerSecond
* prevents throttling
* log the limit so the user realizes it's the script, not the service
* Change to time based instead of request based limits (see momentohq/client-sdk-dotnet#229)
* <strike>totalNumberOfOperationsToExecute</strike> totalMsToRun
* printStatsEveryNMs
* Always print stats at the end.
This probably diverges from the other SDK's load generators.
Closes #123
> feat: More load-gen example options.

- examples/load-gen.ts
* The comments about the config defaults are wrong in a few places. The real value is right there, so remove them.
* totalSecondsToRun was too short.
> fix: Loadgen config comments and defaults.

- examples/load-gen.ts
Before each load-gen worker was showing stats resulting in 10 copies of the same stats. Now it only shows the stats once. This is much easier to read.
> fix: Only show one set of load-gen stats.

- integration/simple-cache-client.test.ts
- src/errors/error-utils.ts
- src/errors/errors.ts
- src/internal/cache-client.ts
- src/internal/control-client.ts
- src/utils/validators.ts
This is a followup to https://github.com/momentohq/client-sdk-javascript/pull/131. It removes unneeded linting directives, tightens up control client and data client validation, adds tests for the validators, and adds documentation for the `applyMixins` function.
> chore: linting and validation fixes

- package-lock.json
npm audit caught a security vulnerability.
https://vulert.com/vulnerability/npm-json5-47903
Should dependabot have caught this?
> chore: fix json5 vulnerability

- integration/simple-cache-client.test.ts
- src/auth/credential-provider.ts
- src/config/configuration.ts
- src/config/configurations.ts
- src/config/transport/transport-strategy.ts
- src/grpc/idle-grpc-client-wrapper.ts
- src/index.ts
- src/internal/cache-client.ts
- src/internal/control-client.ts
- src/simple-cache-client-props.ts
- src/simple-cache-client.ts
- test/simple-cache-client.test.ts
This just takes a quick pass through the client constructors and standardizes on a re-usable interface for the required constructor args, so that they can be passed in the keyword-arg style.  We also rename some variables such as `authProvider` for consistency with the new interface names.
This is the first PR to work towards the list of outstanding tasks described in https://github.com/momentohq/client-sdk-javascript/issues/146 .
> feat: DRY up constructor args, improve consistency of variable names

- src/config/configurations.ts
- src/config/transport/grpc-configuration.ts
- src/config/transport/transport-strategy.ts
This commit introduces a first attempt at a pattern for providing the InRegion pre-built Configurations.  We needed a slightly different pattern here since these configurations are nested one level more deeply inside of the Configurations namespace.
> feat: introduce InRegion pre-built Configurations

- src/config/configurations.ts
As per Schwern's comment on an earlier PR, TS classes do indeed inherit non-default constructors from their parent class, so the constructors for the pre-built configurations are redundant unless the argument list changes.  In this commit we remove them to DRY up the code.
> chore: remove redundant pre-built Configuration constructors

- src/config/configuration.ts
- src/config/configurations.ts
- src/simple-cache-client.ts
When we initially introduced the new Configuration objects, we temporarily removed the plumbing that would allow users to configure logging.  This commit adds the logging configuration back to the Configuration interface and ensures that logging is initialized during client construction.
> feat: re-introduce logging options

- integration/simple-cache-client.test.ts
- src/auth/credential-provider.ts
- src/config/configuration.ts
- src/config/configurations.ts
- src/config/transport/grpc-configuration.ts
- src/config/transport/transport-strategy.ts
- src/errors/errors.ts
- src/internal/cache-client.ts
- src/messages/responses/list-caches.ts
- src/messages/responses/list-signing-keys.ts
- src/simple-cache-client-props.ts
- test/simple-cache-client.test.ts
* First pass at adding missing JSDocs for public APIs
* Removes unused fields (maxConcurrentRequests, certname fields) until we need them
* Renames some duration/size fields to be suffixed with their respective units of measurement
* Migrates places where we were using `| null` to `| undefined` as appropriate
> chore: fill in JSDocs for public APIs, other minor cleanups

- README.template.md
We need to make it clear on the README that there are now APIs in here that you can't use without signing up for the preview features.
> chore: add warning about preview APIs for collections

- src/internal/cache-client.ts
- src/internal/control-client.ts
It was unclear to me that cache.cache_client and control.control_client are GRPC types. They can be confused with the actual client objects.
> refactor: Make it clearer what cache.cache_client is.

- src/messages/responses/cache-list-fetch.ts
- src/utils/display.ts
- test/utils/display.test.ts
In a subsequent PR I'll need this common logic for set-fetch-response.
> chore: refactor common string array display logic for re-use

- integration/set.test.ts
- src/index.ts
- src/messages/responses/cache-set-add-element.ts
- src/messages/responses/cache-set-add-elements.ts
- src/simple-cache-client.ts
For integ-testing, since CacheSetAddElement simply delegates
to CacheSetAddElements, the integ test cases are basic smoke
test cases and are not as exhaustive as CacheSetAddElements
integ test cases.
https://github.com/momentohq/client-sdk-javascript/issues/170
> feat: add CacheSetAddElement that accepts a single element

- src/messages/responses/cache-delete.ts
- src/messages/responses/cache-dictionary-remove-field.ts
- src/messages/responses/cache-dictionary-remove-fields.ts
- src/messages/responses/cache-dictionary-set-field.ts
- src/messages/responses/cache-dictionary-set-fields.ts
- src/messages/responses/cache-set-add-element.ts
- src/messages/responses/cache-set-remove-elements.ts
- src/messages/responses/cache-set.ts
- src/messages/responses/create-cache.ts
- src/messages/responses/delete-cache.ts
- src/messages/responses/response-simple-success.ts
- src/messages/responses/revoke-signing-key.ts
A lot of responses are the same: an empty Success and a simple Error. This avoids having to copy them.
> refactor: DRY the simple success responses.

- .eslintignore
- jest-integration.config.ts
- jest.config.ts
- package-lock.json
- package.json
- tsconfig.json
jest-extended adds a lot of [useful matchers](https://jest-extended.jestcommunity.dev/docs/matchers/) I've been missing from rspec. While I was at it, I upgraded Jest and changed its config to Typescript.
I followed [this example](https://github.com/jest-community/jest-extended/tree/main/examples/typescript/all).
This is extracted from the list ops branch.
> test: Upgrade jest. Add jest-extended.

- src/config/configuration.ts
- src/config/configurations.ts
- src/config/transport/grpc-configuration.ts
- src/config/transport/transport-strategy.ts
- src/internal/cache-client.ts
- test/config/configuration.test.ts
- test/config/transport/transport-strategy.test.ts
This commit makes a small tweak to the constructor signatures for the various classes in the Configuration heirarchy; we now use a Properties interface for each one so that arguments can be passed in keyword-style.  This is with an eye towards some of these argument lists expanding over time, and to make things a bit more consistent / readable.
We also add unit test coverage for the copy constructors for all of these classes, as was requested in an earlier PR.  This addresses one of the fast-follow items from:
https://github.com/momentohq/client-sdk-javascript/issues/146
This change shouldn't have any API implications for existing users as long as they were using one of the pre-built configs.
> chore: add Props interfaces and unit tests for config copy constructors

- src/config/configuration.ts
- src/config/configurations.ts
- src/config/transport/grpc-configuration.ts
- src/config/transport/transport-strategy.ts
- src/grpc/idle-grpc-client-wrapper.ts
- src/internal/cache-client.ts
- test/config/configuration.test.ts
- test/config/transport/transport-strategy.test.ts
This addresses one of the outstanding items from the list
of fast-follows for the Configuration API:
https://github.com/momentohq/client-sdk-javascript/issues/146
Prior to this commit we were exposing 'maxIdleMillis' as a
top-level setting on the Configuration.  However, we do not
expect users to need to know about this setting in the 90%
use case, so this commit moves it down into the TransportStrategy.
> chore: move max idle millis setting into transport strategy

- integration/create-delete-list-cache.test.ts
- integration/dictionary.test.ts
- integration/get-set-delete.test.ts
- integration/integration-setup.ts
- integration/list.test.ts
- integration/set.test.ts
- src/internal/cache-client.ts
While DRYing up the tests, I discovered a bug in how Set is treating cache and set name validations.
Also
* DRY'd up the name validaton tests.
* Added name validation tests to Set.
> fix: Set ops return INVALID_ARGUMENT_ERROR, not raise.

- .github/workflows/build.yml
- .github/workflows/dependency-review.yml
- .github/workflows/manual-release.yml
- .github/workflows/on-push-to-main-branch.yml
- .github/workflows/on-push-to-release-branch.yml
This should quiet the "Node.js 12 actions are deprecated" warnings.
Closes #165
> chore: Update all our off-the-shelf actions.

- integration/dictionary.test.ts
- integration/integration-setup.ts
* Extract shared tests
* Speed up the TTL tests by reducing the timeouts (60s -> 20s)
* Move method tests into individual describe blocks for easier reading.
> refactor: DRY and speed up dictionary tests

- src/errors/errors.ts
- src/simple-cache-client.ts
- tsconfig.json
For some reason, the linter was configured to allow unused local properties. The check is off on nearly all our Typescript repos. There doesn't seem to be a reason not to turn the check on.
Closes #116
> refactor: Turn on noUnusedLocals, fix errors.

- integration/integration-setup.ts
- src/auth/credential-provider.ts
- test/auth/credential-provider.test.ts
- test/simple-cache-client.test.ts
This commit adds StringMomentoTokenProvider alongside the existing
EnvMomentoTokenProvider, for parity with other SDKs.  Also tweaks
the constructor for the auth providers to use an interface, to make
it easier to provide keyword-style arguments for the cases where
you want to override the endpoints.
> feat: add StringMomentoTokenProvider and use interfaces for constructor args

- integration/dictionary.test.ts
- integration/integration-setup.ts
- integration/list.test.ts
- integration/set.test.ts
- src/messages/responses/cache-dictionary-fetch.ts
- src/messages/responses/cache-dictionary-get-field.ts
- src/messages/responses/cache-dictionary-get-fields.ts
- src/messages/responses/cache-dictionary-increment.ts
- src/messages/responses/cache-list-concatenate.ts
- src/messages/responses/cache-list-fetch.ts
- src/messages/responses/cache-list-length.ts
- src/messages/responses/cache-list-push.ts
- src/messages/responses/cache-set-add-elements.ts
- src/messages/responses/cache-set-fetch.ts
- src/messages/responses/cache-set-remove-elements.ts
- src/messages/responses/create-signing-key.ts
- src/messages/responses/list-caches.ts
- src/messages/responses/list-signing-keys.ts
- src/messages/responses/response-base.ts
- src/messages/responses/response-get-value.ts
- src/messages/responses/response-simple-success.ts
The switch from classes to mixins in 8d8757a98257ccc0ed6344e611026e24d7912240 caused many classes to actually be aliases. For example, `CacheDictionaryRemoveField.Success` and `CacheDictionaryRemoveFields.Success` were the same class. That means a response from DictionaryRemoveFields was an instance of both `CacheDictionaryRemoveField.Success` and `CacheDictionaryRemoveFields.Success`. The dictionary tests had several bugs of this kind.
This also confused IDEs, they would report the incorrect return type for responses.
> fix: Differenciate response classes.

- test/simple-cache-client.test.ts
Hardcode a fake auth token in simple-cache-client.test.ts to stop it from requiring the TEST_AUTH_TOKEN environment variable. The auth token was taken from an older version of the test.
> fix: remove environment variable requirement for test

- src/grpc/retry-interceptor.ts
Resend the retrying message and close the old one to make the retry
interceptor work on all retryable error types. Fix found on the grpc
github. Manually tested using the FAILED_PRECONDITION error type.
The changes to the retry interceptor were found [here](https://github.com/grpc/grpc-node/issues/284#issuecomment-415543782).
Using a CHECK_PRECONDITION error caused by a dictionary increment overflow, the code before the fix would get into the retryer but not actually retry:
> Request path: /cache_client.Scs/DictionaryIncrement; response status code: 9; number of retries (0) is less than max (3), retrying.
Increment failed! TIMEOUT_ERROR: The client's configured timeout was exceeded; you may need to use a Configuration with more lenient timeouts: 4 DEADLINE_EXCEEDED: undefined
By adding …
> fix: Make UNAVAILABLE errors retry correctly

- integration/dictionary.test.ts
- src/internal/cache-client.ts
- src/simple-cache-client.ts
Replace the fields array of key value pairs with a Map.
Tested against the integration tests.
> chore: replace dictionary set fields array with map

- integration/dictionary.test.ts
- src/internal/cache-client.ts
- src/messages/responses/cache-dictionary-fetch.ts
- src/messages/responses/cache-dictionary-get-fields.ts
- src/simple-cache-client.ts
This commit makes a few changes to the Dictionary APIs to help
simplify our in-browser demo code.
Changes include:
* DictionarySetFields can now be called with a Record literal input
rather than needing to construct a Map.
* DictionaryFetch and DictonaryGetFields: renamed `valueDictionary*`
value accessor names to `valueMap*` to make it more obvious what
the return type will be.
* DictionaryFetch and DictonaryGetFields: added `valueRecord*` accessors
so that users can avoid dealing with `Map`s if their field names
are strings.
* DictionarySetFields now accepts a Record or a Map as input.
> feat: rename dictionary value accessors, add Record accessors

- src/config/configuration.ts
- src/config/configurations.ts
- src/config/retry/default-eligibility-strategy.ts
- src/config/retry/eligibility-strategy.ts
- src/config/retry/fixed-count-retry-strategy.ts
- src/config/retry/retry-strategy.ts
- src/grpc/retry-interceptor.ts
- src/internal/cache-client.ts
- src/internal/control-client.ts
- src/simple-cache-client.ts
- src/utils/logging.ts
- test/config/configuration.test.ts
This commit introduces the RetryStrategy interface as part of
our Configuration object.  Also introduces the most basic
retry strategy, FixedCountRetryStrategy, and wires it up
to the RetryInterceptor.
This causes some quirkiness with logging initialization and
highlights that the logging API needs to be re-worked a bit.
Will tackle that in a follow-up PR; in the meantime the logger
will log at DEBUG level.
> feat: introduce API for RetryStrategy

- src/config/configurations.ts
- src/config/logging/default-momento-logger.ts
- src/index.ts
- test/config/configuration.test.ts
While updating the examples to use the new logging API, I found a
few things that didn't feel right:
1. The pino logger wasn't exported properly so the imports looked weird
2. It felt weird for users to have to be exposed to the name Pino if they
weren't really interested in digging in to logs.
This commit fixes the imports, and adds DefaultMomentoLoggerFactory
as a wrapper around the Pino factory to make the UX a little better
for users who don't care about the underlying logger details.
> feat: improve logger exports, add DefaultMomentoLoggerFactory

- integration/dictionary.test.ts
- integration/list.test.ts
- integration/set.test.ts
- src/internal/cache-client.ts
- src/simple-cache-client.ts
- src/utils/cache-call-options.ts
Create interfaces for the optional api arguments. This forces them to be
named and lets them be supplied in any order. Methods with only one
optional argument still get an interface for consistency.
> chore: swap truncate and ttl arguments

- src/internal/cache-client.ts
- src/simple-cache-client.ts
As per our naming conversation today we want to standardize on the term 'elements' as a common vocabulary word for the contents of collections.  This commit changes the places in the dictionary API where we were referring to 'items' and replaces it with 'elements'.
> fix: change dictionary argument names from items to elements

- src/config/configuration.ts
- test/config/configuration.test.ts
I had forgotten a hard-fought lesson that I learned in the .NET
SDK (which also needs this fix): the pre-built configurations
will often pass the loggerFactory around to the constructors
of other components that they instantiate, such as the RetryInterceptor.
If this happens, and then we allow the user to override the loggerFactory
on the config with a new one, we can end up in a state where the original
factory is being used for some components and the new one for other
components.  For a short time I attempted to reconcile this by trying
to keep track of all of the places where the loggerFactory had been
referenced and then trying to update those as well, but it was a big
mess that wasn't guaranteed to work so we decided that was a bad path
to go down.
Hence, it is necessary for users …
> fix: remove withLoggerFactory from Configurations

- src/internal/cache-client.ts
- src/simple-cache-client.ts
Return remove field(s) responses instead of get field(s) responses for the remove field and remove fields methods.
Log the correct ttl in the internal set method and fix a couple of warnings.
> fix: fix incorrect return types and logging bug

- integration/list.test.ts
- integration/set.test.ts
- src/messages/responses/cache-list-fetch.ts
- src/messages/responses/cache-set-fetch.ts
In some recent commits we added some niceties for working with Dictionary responses.  In particular we added shorthand-aliases for the `*String` accessors, and we added support for Record types because they are more idiomatic to work with in JS than Map types.
Similarly in this commit we:
* Add shorthand-aliases for the `*String` accessors for Lists
* Add shorthand-aliases for the `*String` accessors for Sets
* Add `valueArray*` accessors alongside the `valueSet*` accessors for Sets, because Arrays are easier to work with in JS and more idiomatic for some workflows.
> feat: add some niceties for working with ListFetch/SetFetch response

- integration/set.test.ts
Make the value array set integration test assertions independent of the order of the returned array.
> fix: make set array test assertions order independent

- src/internal/control-client.ts
- src/simple-cache-client.ts
Remove the page token from the list caches method. Paging is unimplemented and the pagination could be hidden in the sdk once it is.
Remove an out-of-date TODO.
> chore: remove the page token from the list caches method

- src/auth/credential-provider.ts
- src/internal/utils/object.ts
Override the valueOf method in the credential providers to prevent them from including the credential in the returned value.
> chore: Stop the credential provider toString from including the cred

- integration/integration-setup.ts
- src/auth/credential-provider.ts
- test/auth/credential-provider.test.ts
This commit adds some static factory functions for instantiating
CredentialsProviders, to make them a little more discoverable and
user-friendly.
> feat: provide factory functions for instantiating CredentialsProviders

- .github/workflows/build.yml
- .github/workflows/on-push-to-main-branch.yml
- examples/README.md
- examples/advanced.ts
- examples/basic.ts
- examples/package-lock.json
- examples/package.json
This commit splits out the main example into two files: `basic.ts`
and `advanced.ts`.  The `basic.ts` is intended to be a quickstart
so we try to keep it as succint as possible.  The `advanced` example
adds more features such as listCaches, delete, and an example of how
to issue concurrent gets.
> chore: improve example code

- README.template.md
During our recent bug bash it was called out that the link to the
momento-cli for getting an auth token pointed to a fairly verbose
doc.  This commit changes the link to point to our getting started
page, where users can choose between the in-browser approach or
the approach of installing the CLI for their OS.
> chore: better link to CLI for getting auth token

- src/simple-cache-client.ts
Feedback from the bug bash was that using the word "Creating"
would be better than "Instantiating".
> chore: change wording of log message when constructing client

- examples/advanced.ts
- examples/basic.ts
This was called out during the recent bug bash.
> chore: remove redundant string casts in examples

- src/simple-cache-client.ts
Standardize the tsdocs in the simple cache client. Formats them in a consistent way and uses consistent language for descriptions and matching parameters.
I'm not attached to any of the specific language so if we have preferred wording I can update this.
> chore: standardize the simple cache client tsdocs

- src/config/configurations.ts
- test/config/configuration.test.ts
Users may want to avoid the possibility of us making changes to
the tuning settings in our pre-built configs between releases.
This commit renames the current versions to `v1()`, and converts
the `latest()` factory fns into aliases to `v1()`.  This way
in the future we can introduce v2's if necessary without worrying
about rolling out unexpected/undesired config changes to users
who have pinned to v1.
> feat: introduce v1 stable versions of pre-built configs

- examples/advanced.ts
- examples/basic.ts
- examples/dictionary.ts
- examples/load-gen.ts
- examples/package-lock.json
- examples/package.json
This commit updates us the examples to 1.1, and uses the
new v1 versions of the pre-built config objects rather than
the `latest()` versions.
> chore: update examples to 1.1, use static pre-built configs

- integration/get-set-delete.test.ts
Added several tests for `set` operation with `options {ttl: some_ttl}` to make sure ttl works as expected.
I referenced the tests in our .NET SDK: https://github.com/momentohq/client-sdk-dotnet/blob/main/tests/Integration/Momento.Sdk.Tests/SimpleCacheDataTest.cs
Closes #239
> chore: add test coverage for set operation with ttl

- src/internal/cache-client.ts
- src/simple-cache-client.ts
- src/utils/cache-call-options.ts
For `sortedSetFetchByInde`: refactors the start and index index to be optional and part of call options. Also adds `order` to the call options.
> feat: use call options for sorted set fetch, including order

- src/internal/cache-client.ts
- src/simple-cache-client.ts
- src/utils/cache-call-options.ts
Implements `sortedSetFetchByScore`. A future PR will implement the other features of this API, including min/max inclusive vs exclusive flags, limit, and count; as well as testing.
> feat: implement sorted set fetch by score

- src/internal/cache-client.ts
- src/internal/utils/validators.ts
- src/messages/responses/cache-sorted-set-fetch.ts
- test/integration/sorted-set.test.ts
Tweaks a few of the accessor names based on recent conversations.
Adds tests for sortedSetFetchByIndex, including validation for
a few possible error cases for startIndex and endIndex.
> fix: tests for sortedSetFetchByIndex, minor naming fixes

- src/internal/cache-client.ts
- src/internal/utils/validators.ts
- test/integration/sorted-set.test.ts
Adds tests for sortedSetFetchByScore.  Fixes a minor issue where if min/max score were explicitly set to 0, we weren't passing them through to the request because they evaluated as "false-y" when we checked to see if they had been provided.
> fix: add tests for sortedSetFetchByScore, fix minor issue with 0 min/max scores

- README.template.md
- src/auth/credential-provider.ts
- src/cache-client-props.ts
- src/cache-client.ts
- src/config/configuration.ts
- src/config/configurations.ts
- src/index.ts
- src/internal/data-client.ts
- test/integration/get-set-delete.test.ts
- test/integration/integration-setup.ts
- test/unit/cache-client.test.ts
- test/unit/config/configuration.test.ts
This commit renames the primary client object from SimpleCacheClient
to CacheClient, after we received feedback from users that the
name was misleading and seemed to imply that there were multiple
clients to choose from.
The legacy name is retained as a type alias with a deprecation
warning so that this change is backward-compatible.
> feat: rename SimpleCacheClient to CacheClient

- test/integration/sorted-set.test.ts
Prior to this commit we had temporarily disabled some sorted
set tests that were asserting that an empty list would be
returned in cases where the set existed but the requested rank/offset
resulted in an empty list.  The server was returning a MISS
in those cases.  It has since been updated to the expected
behavior so now we re-enable the tests.
> chore: re-enable SortedSet tests that assert empty list response

- src/cache-client.ts
- src/internal/data-client.ts
This just fixes a typo in the internal data client class.
> fix: wrong name for dictionarySetField function in internal data client

- examples/package.json
- examples/request-coalescing.ts
- examples/utils/cache.ts
- examples/utils/load-gen-statistics-calculator.ts
- examples/utils/load-gen.ts
- examples/utils/momento-client-with-coalescing.ts
- Addressed comment feedback 
1. Add request coalescing class that implements gets and sets from the map (with keys as cacheKeys and values as cache response promises) (Thanks Chris for helping me out!)
2. Add metric to record number of get/set requests coalesced
1. Add request coalescing example
- Runs concurrent requests(~200) using the basic load-generator
- Runs conscurrent requests(~200) using the request-coleascer-load-generator
- Prints the histogram and some stats for both the cases as they run for 60 sec. 
1. Refactor overlapping pieces of code to utils
https://github.com/momentohq/dev-eco-issue-tracker/issues/204
1. `npm install`
4. `MOMENTO_AUTH_TOKEN=<YOUR AUTH TOKEN> npm run request-coalescing`
For 200 concurrent requests, ran for 60 sec with 100 requests (max) allowed per …
> chore: Add request coalescer example

- test/integration/create-delete-list-cache.test.ts
- test/integration/get-set-delete.test.ts
- test/integration/integration-setup.ts
This commit fixes a few places where we were still creating
caches in tests that only had UUIDs for their names.  Also fixes
a few tests where we were orphaning those caches after the
tests completed.
> fix: orphaned UUID caches

- src/internal/pubsub-client.ts
- src/internal/subscription-state.ts
- src/messages/responses/topic-subscribe.ts
- src/topic-client.ts
- src/utils/topic-call-options.ts
In the prior PR, the user had no mechanism to unsubscribe / cancel the
stream. In this PR we allow the user to unsubscribe via the subscription response.
We return the response from `subscribe` and also pass it as an argument to the error handler.
See [here](https://github.com/momentohq/client-sdk-nodejs/pull/350/commits/6b6d0268087b66a3cf4449c5f11d232501099cba) for the examples.
> feat: allow user to unsubscribe when receiving an error

- src/config/middleware/experimental-metrics-csv-middleware.ts
We now capture the number of active requests both at the start
and the end of a given request, because it may change a lot
while the request is being processed.
> fix: improve metrics for num active requests

- src/index.ts
- src/internal/pubsub-client.ts
- src/messages/responses/topic-item.ts
- src/messages/responses/topic-subscribe.ts
- src/topic-client.ts
- src/utils/topic-call-options.ts
- test/integration/topic-client.test.ts
- fix: subscribecalloptions should be required
- chore: rename argument to item handler
- refactor: move TopicSubscribe.Item to TopicItem
Addresses #343
> fix: pubsub UX minor fixes and refactor

- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
We will need to pass something along the lines of 
```
CredentialProvider.fromString({
authToken: "token",
controlEndpoint: 'control.<endpoint>',
cacheEndpoint: 'data.<endpoint>'
})
```
Eventually might be nice to have some kind of session token provider, however since we are still messing with what these tokens look like I want to hold off on creating that class
> chore: allow passing of dynamic credentials provider to web sdk

- src/cache-client.ts
- src/internal/data-client.ts
The API for `setIfNotExists` has a typo: the parameter for `value` was mis-named `field`.
> fix: `setIfNotExists` should accept a `value` not `field`

- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/src/internal/control-client.ts
- packages/client-sdk-web/src/ping-client.ts
- packages/common/src/index.ts
- packages/common/src/internal/clients/cache/index.ts
- packages/common/src/internal/clients/index.ts
anywhere where we are consuming the common library, we should be importing directory from the package `@gomomento/common`, instead of finding it within the `dist/` directory. This seems to be breaking the library inside of the browser
> fix: export all utils/responses/clients from common lib

- src/internal/pubsub-client.ts
Prior to this we only passed `NOT_FOUND` gRPC errors to the user's error handler. We should invoke the error handlers on other errors but not subscribe.
> fix: pass other errors to user's subscribe error handler

- src/index.ts
Prior to this commit, there were quite a few types that were
not exported from the main index.  This meant that if you needed
to reference them in your code your import statement would include
the `dist/src` dir explicitly, which is leaking implementation
details.  This is also problematic for the case where we want
to split out a common/core package because those paths would
change.
To remedy that, this commit adds explicit exports for all of the
types that were missing.  Once this is merged we can do a release
and then start working on merging the feature branch back in.
> chore: add all public types to interface

- .github/workflows/on-push-to-release-branch.yml
- packages/core/package.json
- scripts/build-all-packages.sh
- scripts/publish-all-packages.sh
- scripts/publish-package.sh
This commit adds shell scripts to simplify the steps for publishing
to npm.js.  As of this commit, the release process should only
release the `core` package.  Since nothing will be consuming it
yet, this should be harmless.  In subsequent commits we will
* add polling to wait for the publish to complete
* publish the nodejs package with a dep on the newly published
core package
* figure out pre-1.0 versioning for the web sdk package
* publish the web sdk package.
> feat: publish core package to npm.js

- scripts/publish-package.sh
At some point recently npm.js started requiring you to pass
the 'public' access flag to publish public packages, otherwise
the publish fails with an error about how you have to pay for
private packages.
> fix: pass 'public' flag to npm publish

- scripts/wait-for-npmjs-release.sh
The previous commit waited 20 minutes for the core package to be
available on npm.js before moving forward to the node.js release
task.  That did not turn out to be long enough, so we timed out.
This commit increases it to 1 hour.
> chore: increase the wait time for publishing core package

- scripts/publish-all-packages.sh
- scripts/publish-package.sh
Prior to this commit we weren't updating the package.json
files until after we ran tests and such, which is not the
right order to do it.
We were also missing a build step for building the common
integration tests before publishing the node.js sdk.
> chore: fix order of updating package.json for publish

- scripts/publish-all-packages.sh
In the previous commit we did a dry run testing that the
pre-release version number for the web sdk was constructed
correctly.  Now we are ready to actually do a release to
npm.js.
> feat: enable web sdk pre-release to npm.js

- scripts/publish-all-packages.sh
- scripts/publish-package.sh
The web SDK publish script is modifying the version number for
pre-1.0 releases for now, but prior to this commit it was also
using that same munged version number for specifying it's
dependency on @gomomento/core.  We need to use the real version
number for the core dependency; this commit updates the scripts
to require two version arguments, one for the package version
and one for the core dependency version.
> fix: core dependency version for web sdk

- packages/client-sdk-web/src/index.ts
For some reason, these comments here cause errors like 
`CredentialsProvider` is undefined 
during runtime. Tslint/eslint checks pass just fine. Removing these comments fixes the issue, and the `CredentialsProvider` will import correctly
> fix: comments in import/export statements causing runtime errors

- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/core/src/messages/responses/response-base.ts
A user noticed that our `innerException` signatures were declaring
that they returned `object`, when in actuality they always return
an SdkError.  This commit fixes the signature so that end users
can do more useful things with the Errors.
> fix: change error type to concrete type rather than `object`

- packages/common-integration-tests/src/list.ts
We have seen some transient build errors that look like
```
TypeError: respFetch.valueListString is not a function
109 |         );
110 |         expect(
> 111 |           (respFetch as CacheListFetch.Hit).valueListString()
|                                             ^
112 |         ).toIncludeAllMembers(values);
113 |       });
114 |     };
at Object.<anonymous> (../common-integration-tests/src/list.ts:111:45)
```
This is happening because in our integration tests, we are casting the response type before asserting the type of the response. This pr fixes this by asserting the response is of the right type before casting and verifying the contents of the response
> fix: verify response types before casting them

- packages/client-sdk-web/src/internal/data-client.ts
browsers don't have access to `utils` to import `TextEncoder`. Inside the browser, `TextEncoder` and `TextDecoder` are globally available, so just removing the import should fix the current issue I am facing
```
Uncaught TypeError: util_1.TextEncoder is not a constructor
```
> fix: don't import text encoder from utils

- packages/core/src/internal/clients/auth/AbstractAuthClient.ts
- packages/core/src/internal/clients/auth/IAuthClient.ts
this pr plumbs through the optional `validForSeconds` args from the abstract auth client, down to the web/nodejs sdks
> fix: add optional arg for validForSeconds

- .github/workflows/on-push-to-release-branch.yml
This change prevents developers from manually triggering a new release from the release branch
> fix: remove release footgun

- scripts/publish-package.sh
Prior to this commit the package-lock.json file for the SDK projects
is hard-coded to the 0.0.1 version of core; we then modify the package.json
file to depend on the new version, but attempt an `npm ci` without
updating the package-lock.json first.  In this commit we tweak the
publish logic to do an `npm install` on the appropriate version of
core before we do the `npm ci`.  This should cause the package-lock.json
file to get updated correctly prior to publishing.
> fix: package-lock.json invalid when installing core dependency for publishing

- scripts/publish-package.sh
npm seems to get confused if you try to run `npm install` on a
package that you already have a local relative reference to,
so in this commit we remove the sdk-core dep before attempting
install the new released version of it during a publish.
> fix: uninstall relative sdk-core package before installing released version

- scripts/publish-all-packages.sh
- scripts/publish-package.sh
- scripts/update-package-versions.sh
We get type incompatibilities from version mismatches if the common-integration-tests
package is not built against the released version of sdk-core during the publish
steps.  This commit updates publish so that it bumps dependency versions for the
integration tests package before attempting to build/publish the sdks.
> fix: common-integration-tests needs to use the released sdk-core during publish

- scripts/build-all-packages.sh
- scripts/build-and-test-all-packages.sh
- scripts/build-and-test-package.sh
- scripts/build-package.sh
- scripts/publish-all-packages.sh
- scripts/publish-package.sh
- scripts/update-package-versions.sh
- scripts/wait-for-npmjs-release.sh
During publish we were referencing common-integration-tests package
via a relative path.  This meant that it had its own node_modules
directory.  This meant that classes from `sdk-core` were present
in two different node_modules directories, which makes npm very
unhappy when you are doing things like testing than an object is
an instance of a certain class.
In this commit, during the publish phase, we do an npm pack on the
integration tests and then use that as the dep for the SDKs.  That
way they don't try to use anything from the int tests node_modules
dir.
> fix: use a packed version of common integration tests during publish

- packages/core/src/messages/responses/generate-api-token.ts
users should only be able to access the members from the response class by using the public getters, rather than accessing the members themselves
> chore: make GenerateApiTokenResponse members private

- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/create-delete-list-cache.ts
- packages/common-integration-tests/src/dictionary.ts
- packages/common-integration-tests/src/get-set-delete.ts
- packages/common-integration-tests/src/list.ts
- packages/common-integration-tests/src/set.ts
- packages/common-integration-tests/src/sorted-set.ts
This commit adds an `expectWithMessage()` method that extends the built-in Jest `expect()` functionality by allowing users to supply extra details in a message for display when the assertion fails. For example, we can call `.toString()` on responses to get extra details about them:
```
expectWithMessage(() => {
expect(result).toBeInstanceOf(CacheSortedSetGetRank.Hit);
}, `expected HIT but got ${result.toString()}`);
```
> chore: add expect messages

- packages/common-integration-tests/src/sorted-set.ts
An issue with `grpc-js` is causing the `SortedSetGetRank` operation to return `undefined` as the rank value for the topmost (0-th ranked according to sort order) item in the set. All other rank values are fine, and the same behavior is not observed with `grpc-web` and the web sdk.
This commit introduces a test to demonstrate the bug as well as a temporary workaround that detects the combination of a `hit` cache result and an undefined rank value and changes the rank to zero. This will prevent the top-ranked item in a sorted set from being mishandled as a cache miss. This change is intended to be removed when a root cause and remediation are found.
> chore: add better test coverage for sortedSetGetRank

- packages/client-sdk-web/src/internal/auth-client.ts
Remove logger from generate auth token api:
When calling the "generateAuthToken" api from console, I encountered the following error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'debug')
at InternalWebGrpcAuthClient.generateAuthToken (auth-client.ts:47:17)
at AuthClient.generateAuthToken (AbstractAuthClient.ts:25:34)
at generateAuthToken (controlplane-store.ts:114:5)
at onClickGenerateToken (Tokens.tsx:56:26)
at onClick (Tokens.tsx:200:30)
at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
at invokeGuardedCallback (react-dom.development.js:4277:31)
at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
at executeDispatch …
```
> fix: remove logger from generate auth token api

- packages/client-sdk-nodejs/src/auth-client.ts
- packages/client-sdk-nodejs/src/internal/auth-client.ts
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/core/src/internal/clients/auth/AbstractAuthClient.ts
- packages/core/src/internal/clients/auth/IAuthClient.ts
In the not-too-distant future we will need to support generating
auth tokens using other auth tokens.  This commit renames the
arguments in the various function signatures to just `token` so
that it won't be misnamed when we do support that.
> feat: rename sessionToken param to token

- scripts/build-and-test-package.sh
I added this flag a while back because without it, too many concurrent
tests will run on developer laptops and you get throttling errors.
I had added maxWorkers=1 to the script to allow the tests to pass on
my laptop, but did not mean to commit that for prod.
> fix: remove maxWorkers=1 flag for prod

- packages/client-sdk-web/src/internal/auth-client.ts
- packages/client-sdk-web/src/internal/client-metadata-provider.ts
- packages/client-sdk-web/src/internal/control-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/ping-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/utils/web-client-utils.ts
Change web sdk agent to 'js-web'.
Switch from an interceptor to metadata for supplying the agent string
since interceptors don't work for the majority of clients.
Make a client metadata provider that provides the agent and
authorization headers.
Combine the deadline and cache name metadata into one call.
> chore: Differentiate web from nodejs agent

- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/client-sdk-web/src/internal/control-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/ping-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/utils/web-client-utils.ts
We are using distinct DNS names for the grpc-web endpoints to give
us maximum flexibility on the server going forward. This commit updates
the web SDK clients to use the new prefix.
> feat: use new `web.` prefix for DNS names for web sdk

- packages/core/src/index.ts
Some libraries require unit tests (mocks) in addition to integration tests. 
Therefore our integrations need to use dependency injection on the interface
`ICacheClient` so we can mock out `CacheClient` in the tests.
Currently we are not exporting `ICacheClient` from the Node.js or web
SDKs. Left alone we would have to separately install `@gomomento/core` to
access `ICacheClient`, which is less than desirable. After this PR I
will follow up to re-export `ICacheClient` from the SDKs.
> chore: export ICacheClient from core

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
Allow consumers of the SDKs direct access to `ICacheClient` without
having to separately install `@gomomento/core`
> chore: export `ICacheClient` from SDKs

- examples/web/package-lock.json
- examples/web/package.json
For some reason the web sdk's examples package.json file was listing a
dependency on gprc-js, which it doesn't actually need. This commit
removes the unnecessary dependency.
> fix: remove unnecessary grpc dep

- examples/nodejs/doc-examples-js-apis.ts
- scripts/build-nodejs-sdk.sh
`
SDK 'javascript' is missing 50 snippets and 0 files.
Missing snippets: API_ConfigurationLambda,API_DictionaryFetch,API_DictionaryGetField,API_DictionaryGetFields,API_DictionaryIncrement,API_DictionaryRemoveField,API_DictionaryRemoveFields,API_DictionarySetField,API_DictionarySetFields,API_DictionaryLength,API_SetAddElement,API_SetAddElements,API_SetFetch,API_SetRemoveElement,API_SetRemoveElements,API_SetContainsElement,API_SetContainsElements,API_SetLength,API_TopicSubscribe,API_TopicPublish,API_InstantiateTopicClient,API_SortedSetPutElement,API_SortedSetPutElements,API_SortedSetFetchByRank,API_SortedSetFetchByScore,API_SortedSetGetScore,API_SortedSetGetScores,API_SortedSetRemoveElement,API_SortedSetRemoveElements,API_SortedSetGetRank,AP …
> feat: add list api examples for docs

- examples/nodejs/doc-examples-js-apis.ts
This commit adds the examples for all dictionary APIs except "DictionaryLength" which is not implemented in NodeJS and Web SDK yet.
Locally tested via command:
`MOMENTO_AUTH_TOKEN=<MOMENTO_AUTH_TOKEN> npm run doc-examples-js-apis`
> feat: Add dictionary api examples for docs

- examples/nodejs/doc-examples-js-apis.ts
`SDK 'javascript' is missing 32 snippets and 0 files.
Missing snippets: API_ConfigurationLambda,API_DictionaryLength,API_SetAddElement,API_SetAddElements,API_SetFetch,API_SetRemoveElement,API_SetRemoveElements,API_SetContainsElement,API_SetContainsElements,API_SetLength,API_TopicSubscribe,API_TopicPublish,API_InstantiateTopicClient,API_SortedSetPutElement,API_SortedSetPutElements,API_SortedSetFetchByRank,API_SortedSetFetchByScore,API_SortedSetGetScore,API_SortedSetGetScores,API_SortedSetRemoveElement,API_SortedSetRemoveElements,API_SortedSetGetRank,API_SortedSetIncrementScore,API_SortedSetLength,API_SortedSetLengthByScore,API_Ping,API_KeyExists,API_KeysExist,API_UpdateTtl,API_IncreaseTtl,API_DecreaseTtl,API_ItemGetTtl`
This commit adds …
> feat: Add set api examples for docs

- examples/nodejs/doc-examples-js-apis.ts
`SDK 'javascript' is missing 27 snippets and 0 files.
Missing snippets: API_ConfigurationLambda,API_DictionaryLength,API_SetContainsElement,API_SetContainsElements,API_SetLength,API_TopicSubscribe,API_TopicPublish,API_InstantiateTopicClient,API_SortedSetPutElement,API_SortedSetPutElements,API_SortedSetFetchByRank,API_SortedSetFetchByScore,API_SortedSetGetScore,API_SortedSetGetScores,API_SortedSetRemoveElement,API_SortedSetRemoveElements,API_SortedSetGetRank,API_SortedSetIncrementScore,API_SortedSetLength,API_SortedSetLengthByScore,API_Ping,API_KeyExists,API_KeysExist,API_UpdateTtl,API_IncreaseTtl,API_DecreaseTtl,API_ItemGetTtl`
This commit adds examples for the following sorted set APIs except "SortedSetLength" and …
> feat: Add sorted set api examples for docs

- examples/nodejs/doc-examples-js-apis.ts
`SDK 'javascript' is missing 17 snippets and 0 files.
Missing snippets: API_ConfigurationLambda,API_DictionaryLength,API_SetContainsElement,API_SetContainsElements,API_SetLength,API_SortedSetLength,API_SortedSetLengthByScore,API_Ping,API_KeyExists,API_KeysExist,API_UpdateTtl,API_IncreaseTtl,API_DecreaseTtl,API_ItemGetTtl,API_TopicSubscribe,API_TopicPublish,API_InstantiateTopicClient`
This commit adds examples for topic apis:
- InstantiateTopicClient
- Publish
- Subscribe
Locally tested via command:
`MOMENTO_AUTH_TOKEN=<MOMENTO_AUTH_TOKEN> npm run doc-examples-js-apis`
> feat: Add topic examples for docs

- package-lock.json
- packages/client-sdk-nodejs/src/config/configuration.ts
- packages/client-sdk-nodejs/src/config/topic-configuration.ts
- packages/client-sdk-nodejs/src/config/topic-configurations.ts
- packages/client-sdk-nodejs/src/internal/control-client.ts
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-nodejs/src/internal/grpc/idle-grpc-client-wrapper.ts
- packages/client-sdk-nodejs/src/internal/ping-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/topic-client-props.ts
- packages/client-sdk-web/src/config/topic-configuration.ts
- packages/client-sdk-web/src/config/topic-configurations.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/topic-client-props.ts
Prior to this commit, the TopicClient was using a CacheClient
Configuration object for configuration. There are many settings
on the CacheClient configuration that aren't relevant for Topics,
and soon the reverse will likely be true as well. This commit changes
the TopicClient constructor to take a new TopicConfiguration object
which will give us the ability to define the configuration API for the
two clients independently going forward.
> feat: create new TopicConfiguration class for configuring TopicClient

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
Prior to this commit we weren't exporting the topic config namespaces
from the index, so they weren't easy to use from outside of the SDK.
> feat: export new TopicConfiguration namespaces from index

- .github/workflows/build.yml
- examples/web/cache/advanced.ts
- examples/web/cache/basic.ts
- examples/web/cache/dictionary.ts
- examples/web/cache/package-lock.json
- examples/web/cache/package.json
- examples/web/cache/readme.ts
- examples/web/cache/utils/jsdom.ts
Prior to this commit, we had been having trouble with some scenarios
when trying to use the Web SDK in example node.js programs. This is
because there are a few things that the grpc-web library depends on
that are generally only available in browsers, not in node.js.
We had added a dep on the `xhr` library to give us an implementation
of XmlHttpRequest, which allowed most of the basic examples to work.
However, some cases were still not working, including topic subscriptions
(which uses grpc streaming rather than only unary requests).
After digging into this I observed that the jest setup for the web SDK
tests was using a library called JSDom to set up a browser-compatible
environment, and the topic subscriptions were working fine there.
In this commit I have added an `initJSDom` function …
> chore: migrate web sdk examples to use JSDom

- .github/workflows/build.yml
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/client-sdk-web/src/internal/control-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/ping-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/utils/web-client-utils.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/internal/ping.test.ts
- packages/client-sdk-web/test/unit/utils/web-client-utils.test.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/core/src/auth/credential-provider.ts
- packages/core/test/unit/auth/credential-provider.test.ts
- scripts/make-localhost-token-from-dev-token.sh
This commit makes some refactors to the CredentialProvider, as well
as a few minor test changes, to allow the integration tests to be
run against localhost. Changes include:
* Keep track of whether the endpoints for CredentialProvider were
overridden at construction time so that we can branch accordingly.
* Don't add `web` prefix if the endpoints were explicitly overridden.
* Add support for a `MOMENTO_SDK_TESTS_USE_LOCALHOST` in the integration
tests; if provided it will override the endpoints to localhost, and
cause most control plane operations to be skipped.
> chore: Allow Web SDK integration tests to be run against localhost

- .github/workflows/on-push-to-release-branch.yml
The tests don't need a hard-coded cache name and they don't work
well with one anymore; this commit removes the TEST_CACHE_NAME
env var from the release job.
> fix: remove TEST_CACHE_NAME from release job

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
bumping from 1.8.14 -> 1.8.17
Features/fixes that come with this upgrade
- Ensure status and error events are consistently emitted 
- Fix a memory leak that could result from a specific pattern of recursive function 
- Fix missing transport trace 
- Disallow pick_first LB policy as the direct child of an outlier_detection LB policy
> feat: bump grpc js to version 1.8.17

- examples/nodejs/aws/doc-example-files/doc-examples-js-aws-secrets.ts
Addresses #612, creates the example in the JS SDK to pull into the [AWS Secrets doc page](https://docs.momentohq.com/develop/integrations/aws-secrets-manager#example-code-for-aws-secrets-manager).
This is a follow-up PR to #648 as I belatedly realized the docs repo expects [examples from different SDKs](https://github.com/momentohq/public-dev-docs/blob/92dd8e370fb778d997c848c17f3137f660e37fa4/plugins/example-code-snippets/src/inject-example-code-snippets.ts#L62C1-L73C3) to have the [same snippetId](https://github.com/momentohq/client-sdk-java/blob/82abae9f699097eaa649724b41257b48e4315ee8/examples/cache-with-aws/src/main/java/momento/client/example/doc_examples/DocExamplesJavaAPIs.java#L13C22-L13C69).
> fix: renamed aws secrets example to match docs snippetId used by the java example

- examples/nodejs/token-vending-machine/README.md
- examples/nodejs/token-vending-machine/lambda/config.ts
- examples/nodejs/token-vending-machine/lambda/handler.ts
- examples/nodejs/token-vending-machine/lambda/package-lock.json
- examples/nodejs/token-vending-machine/lambda/package.json
- examples/web/vite-chat-app/src/App.tsx
- examples/web/vite-chat-app/src/utils/momento-web.ts
Addresses the first part of [#385](https://github.com/momentohq/dev-eco-issue-tracker/issues/385) by creating a new config file where users can specify token permissions and expiry before deploying the token vending machine. Instructions are in the README and examples are in the `config.ts` file.
The TVM CDK stack can be successfully deployed and a locally running vite-chat-app will get a new token from the API gateway endpoint. However, the app was expecting a string rather than a JSON object (which is what the TVM was providing) so I made a change there to accept JSON instead. The app was also using the wrong environment variable name for the cache name so I fixed that as well. I also had to include the CORS header in the Lambda response so that the app would connect to it.
> feat: allow configurable token vending machine (permission scope and expiry)

- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-csv-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-logging-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
- packages/client-sdk-nodejs/src/internal/middleware/in-flight-request-count-middleware.ts
This commit refactors the "Experimental Metrics CSV" middleware to
be an abstract class that is destination-agnostic. This will allow
us to provide implementations of it that write to other targets
besides CSV. Also included in this PR is an implementation that
writes the metrics to the logger, which is a slightly more scalable
destination for most of our users to consider enabling.
> feat: add logging implementation of experimental metrics middleware

- examples/nodejs/observability/package-lock.json
- examples/nodejs/observability/package.json
This commit updates the version of the `@grpc/grpc-js` dependency such that its transitive dependency with `protobufjs` is bumped to the latest: 7.2.4. Prior versions had a vulnerability which is addressed in this latest version.
> fix: update dependencies to resolve dependabot alert

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/common-integration-tests/package-lock.json
- packages/common-integration-tests/package.json
- packages/core/package-lock.json
- packages/core/package.json
This commit updates to the latest version of our client-protos,
which includes updating to the latest grpc-js. This will pick up
the following changes from upstream:
* Implement channel idle timeout and the channel option grpc.client_idle_timeout_ms (#2471)
* Implement gRFC A62: pick_first: sticky TRANSIENT_FAILURE and address order randomization (#2511)
* Fix premature leaving of context due to improper Http2ServerCallStream handling (#2501 contributed by @CedricKassen)
* Add channel option grpc-node.tls_enable_trace to enable Node TLS tracing (#2507)
* Cancel deadline timer on server when call is cancelled (#2508)
* Added grpc.experimental.createResolver
* Fix propagation of UNIMPLEMENTED error messages (#2528)
* Fix a crash when the channel option grpc.keepalive_permit_without_calls is …
> feat: update grpc-js for keepalives and grpc-web for wasm compat

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/common-integration-tests/package-lock.json
- packages/common-integration-tests/package.json
- packages/core/package-lock.json
- packages/core/package.json
This commit enables keepalive settings in the grpc-js library. In cases such as when a client has been idle for a period of time, these settings should help ensure that the client detects the issue earlier and re-establishes a new connection.
> feat: enable keepalives in nodejs

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
Prior to this commit, the @types/google-protobuf dep was a dev
dependency rather than a regular dependency.
This meant that when we published the SDK, it wasn't treated as
a required dependency for end users. This is problematic because
our middleware API includes the protobuf `Message` type.
I'm not sure what changed recently; possibly something in the
upstream grpc-js library, but for whatever reason this started
causing build failures in the example projects when trying to
build them against 1.30.0. They were failing with an error
about missing the type definition for `Message`.
This commit makes the types dependency a first-class dep. We
will need to be a little careful about this, it's not ideal to
be exposing types from an upstream dependency in our API signatures
and at some point …
> fix: make protobuf types a regular dependency

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/configurations.ts
- packages/client-sdk-nodejs/src/config/transport/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/transport-strategy.ts
- packages/client-sdk-nodejs/test/unit/config/configuration.test.ts
- packages/client-sdk-nodejs/test/unit/config/transport/transport-strategy.test.ts
Make the number of data clients a cache client creates configurable. 6 is likely too many for lambdas as the extra latency for the first 6 calls isn't worth it in a short-lived environment.
Create a new configuration, InRegion.Lambda, for use inside lambdas. It only creates 1 data client instead of 6.
> feat: add a configuration for lambda

- .github/workflows/build.yml
A [previous PR](https://github.com/momentohq/client-sdk-javascript/pull/713) added building the nextjs chat app to the CI workflow. This commit adds the same for the vite chat app.
> chore: add chat examples build to CI

- examples/cloudflare-workers/README.md
- examples/cloudflare-workers/web-sdk/.dev.vars
- examples/cloudflare-workers/web-sdk/README.md
- examples/cloudflare-workers/web-sdk/src/worker.ts
Most tokens that users will have access to in a CloudFlare environment probably
won't have permissions to create a cache. Therefore this example removes the
call to `CreateCache` from the Web SDK example.
Also:
* Adds more logging to make it easier to debug in a deployed environment
* Minor tweaks to the organization of the README to prepare for alternate ways
to set up auth in the near future.
> chore: tweaks to cloudflare Web SDK example docs, remove createCache call

- CONTRIBUTING.md
- packages/client-sdk-nodejs/package.json
- packages/common-integration-tests/package.json
- scripts/build-nodejs-sdk-for-lambda.sh
- scripts/build-package-lambda.sh
Updated ```CONTRIBUTING.MD``` to assist with testing out local SDK changes through examples on ec2/laptop/lambda. Was writing this while waiting for lambda runs to not forget about it later :)
> chore: updating contributing guide to run examples with local SDK changes

- examples/fastly-compute/README.md
- examples/fastly-compute/src/index.ts
Follow up to #728 to emphasize that our example uses Config Stores because Secret Stores are currently restricted to Fastly beta users, but in production environments, Secret Stores should be used to hold auth tokens instead Config Stores.
> chore: update fastly readme to explain secret store vs config store usage

- packages/client-sdk-nodejs/src/cache-client-props.ts
- packages/client-sdk-nodejs/src/cache-client.ts
Make eager connections as default unless otherwise specified in factory methods. Only if a client specifies the value as 0 will the eager connection be turned off. The reason I chose 0 over `undefined` is `undefined` is our indicator that we need to use the default value of 30 seconds.  
I need this to be able to then cut a release and then change examples to use the new version to add stuff for some of the new config. I tested locally and it works fine!
> feat: make eager connections as default unless otherwise specified in factory methpds

- packages/client-sdk-nodejs/src/config/middleware/example-async-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-request-logging-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/middleware.ts
- packages/client-sdk-nodejs/src/internal/grpc/middlewares-interceptor.ts
- packages/client-sdk-nodejs/src/internal/middleware/in-flight-request-count-middleware.ts
This commit changes the middleware API signatures so that they
no longer directly reference objects from the grpc-js and protobuf
libraries.
Prior to this change, any project that included a custom middleware
implementation would need to be very careful to ensure that its
grpc-js and protobuf dependency versions exactly matched those
of the Momento SDK. And when the Momento SDK updates to new versions
of those deps, consuming projects would be forced to update accordingly.
Failure to do so would result in cryptic errors about object types
not being assignable.
Now we provide our own Middleware* classes that decorate the underlying
protobuf/grpc-js libs. This means that consuming projects with custom
middleware will only depend on our API, and our transitive deps will
be hidden from them.
> feat: Don't leak grpc-js/protobuf objects through middleware API

- examples/nodejs/lambda-examples/simple-get/lambda/simple-get/handler.ts
Remove the metrics middleware from the simple get lambda example. It is only required for performance testing/troubleshooting and is confusing for people trying to simply set up a Momento node lambda.
> chore: remove metrics middleware from lambda example

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/control-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/control-client.ts
- packages/common-integration-tests/src/create-delete-list-cache.ts
- packages/core/package-lock.json
- packages/core/src/messages/cache-info.ts
protos now contains cache limits around 
```
// The amount of transactions per second that can be exercised
uint32 max_traffic_rate = 1; 
// The amount of traffic per second that can be exercised in KiB
uint32 max_throughput_kbps = 2;
// The maximum size of a single item in KiB
uint32 max_item_size_kb = 3;
// The maximum TTL allowed for a single item, in seconds
uint64 max_ttl_seconds = 4;
```
and topic limits around
```
// The amount of messages that can be published per second
uint32 max_publish_rate = 1;
// The maximum amount of active subscriptions per cache
uint32 max_subscription_count = 2;
// The maximum size of a single publish message, in KiB
uint32 max_publish_message_size_kb = 3;
```
unblocks ui for https://github.com/momentohq/momento-console/issues/293
> feat: bump protos to support list caches with metadata around limits

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/core/src/internal/utils/validators.ts
Noticed while wiring the same on Python SDK that we need a validation for a better UX
> chore: add validation for eager connection timeout

- packages/core/test/unit/clients/imomentocache-interface.test.ts
Replace the non-null assertions in imomentocache-interface.test.ts with explicit null checks to fix the warnings appearing in prs on GitHub.
> chore: Remove non-null assertions that GitHub doesn't like

- .github/workflows/build.yml
The `--auto` flag just tells github to automatically merge the pr once all checks have passed. We currently have branch protection set to prevent this, however we are already waiting for all checks to pass anyways before we are trying to merge this pr
> fix: merge dependabot prs without the --auto flag

- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-logging-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
Add regular logging of event loop delay and utilization to the metrics logging middleware. The built-in performance monitor doesn't work well in a per-request context, so we log event loop stats on a one-second interval.
> feat: Add event loop delay logging to the metrics logging middleware

- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/common-integration-tests/package.json
- packages/common-integration-tests/src/dictionary.ts
- packages/common-integration-tests/src/get-set-delete.ts
- packages/common-integration-tests/src/list.ts
- packages/common-integration-tests/src/set.ts
- packages/common-integration-tests/src/sorted-set.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/messages/responses/cache-dictionary-fetch.ts
- packages/core/src/messages/responses/cache-dictionary-get-field.ts
- packages/core/src/messages/responses/cache-dictionary-get-fields.ts
- packages/core/src/messages/responses/cache-dictionary-increment.ts
- packages/core/src/messages/responses/cache-get.ts
- packages/core/src/messages/responses/cache-increment.ts
- packages/core/src/messages/responses/cache-list-fetch.ts
- packages/core/src/messages/responses/cache-list-pop-back.ts
- packages/core/src/messages/responses/cache-list-pop-front.ts
- packages/core/src/messages/responses/cache-set-fetch.ts
- packages/core/src/messages/responses/cache-sorted-set-fetch.ts
- packages/core/src/messages/responses/cache-sorted-set-get-score.ts
- packages/core/src/messages/responses/cache-sorted-set-get-scores.ts
- packages/core/src/messages/responses/cache-sorted-set-increment-score.ts
This commit includes the following two major changes:
* All relevant `Hit`/`Success` classes now have a `value()` function,
which returns the data type that we expect to be the most commonly
used one for the response.
* All relevant `Response` classes now have a `value()` function that
returns the `Hit`/`Success` subclass's `value()` for the happy path,
or `undefined` for the `Miss`/`Error` path.
This should simplify a lot of example code, so that we don't have to
call `valueRecord` or similar explicitly specified accessors, and we
can now access `value()` without doing an `instanceof` check first
(even in TypeScript).
NOTE: it is crucially important that we review the choice of data
types for each `value()` function closely and make sure that we
are all aligned on those choices before …
> feat: add value accessors on all relevant response classes

- packages/client-sdk-nodejs/src/internal/data-client.ts
- packages/client-sdk-web/src/internal/data-client.ts
- packages/common-integration-tests/src/get-set-delete.ts
This PR fixes a bug with `setIfNotExists` where the client provided`ttl` is interpreted as `milliseconds` instead of `seconds`. Note that some clients might have noticed this already and treated this as a `feature not bug`, and their contract for the `ttl` they provide is going to break. We're probably okay with this since the API is fairly new in this SDK? The PR has two commits:
- [Commit](https://github.com/momentohq/client-sdk-javascript/pull/792/commits/2a8a6e42a0475da87bd62d5d5993f62769f4b3bb) simply adds an integration test that sets the TTL to be `1000`, and calls `getItemTTL` to try and assert that the remaining TTL is `> 950 seconds`, and expectedly fails due to the bug.
- [Commit](https://github.com/momentohq/client-sdk-javascript/pull/792/commits/f1bb3d01110ae007fdf6d2c5c10623d …
> chore: add integration test that asserts the remaining ttl for setIfNotExists to be valid

- examples/nodejs/token-vending-machine/infrastructure/package-lock.json
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/config.ts
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/handler.ts
- examples/web/nextjs-chat/src/app/api/momento/token/config.ts
- examples/web/nextjs-chat/src/app/api/momento/token/route.ts
- examples/web/vite-chat-app/src/App.tsx
Addresses [#422](https://github.com/momentohq/dev-eco-issue-tracker/issues/422). Updates both static and dynamic token vending machine examples to use generateDisposableToken instead of generateAuthToken.
Plus a bug fix for the Vite chat app to allow ReadWrite access to users if they haven't set the auth method to "cognito".
> chore: update both TVM examples to vend disposable tokens

- .github/workflows/build.yml
- .github/workflows/codeql.yml
This commit cancels in progress jobs instead of letting them run to completion. It should save us quite a bit on gh actions minutes, and will prevent dependabot from prematurely merging prs.
This pr is currently only cancelling the `build.yml` jobs https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
If we wanted to, we could try cancelling _all_ stale jobs https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run
Not sure which is the best strategy to go with, open to changing it to cancel all jobs
> fix: cancel stale workflows

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/configurations.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/vector-index-control-client.ts
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-nodejs/src/preview-vector-index-client.ts
- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/src/internal/cache-control-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/vector-index-control-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/src/preview-vector-index-client.ts
Prior to this commit, we had a single internal ControlClient that housed the control plane APIs for both cache and vector products. This client required an instance of CacheConfiguration for its constructor, which didn't make sense for the Vector use case, so we had a bit of a hack in place to bridge it while we got the public API released.
This commit splits up the internal control client into two so that we don't have to munge the Config object. Also makes sure that all of the Vector classes are prefixed with VectorIndex for consistency.
> chore: split up internal control client between vector and cache functions

- packages/common-integration-tests/.eslintrc.json
- packages/common-integration-tests/jest.config.ts
- packages/common-integration-tests/package-lock.json
- packages/common-integration-tests/package.json
- packages/common-integration-tests/src/auth-client.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/momento-jest-matchers.ts
- packages/common-integration-tests/tsconfig.json
Follow up to #785 to clean up the integration tests and add a new one to show disposable tokens work for the usual cache and topic permissions too.
> chore: clean up disposable token integration tests and add one for cache and topic permissions

- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/src/utils/web-client-utils.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
- packages/client-sdk-web/test/unit/utils/web-client-utils.test.ts
- packages/core/src/auth/credential-provider.ts
- packages/core/src/internal/utils/auth.ts
- packages/core/test/unit/auth/credential-provider.test.ts
Our credential providers support overriding the endpoints, although we do not publicize this and I do not believe any users are using it yet.
As we have added more endpoints this has begun to get unwieldy. This commit simplifies things so that it is possible to override only the base endpoint, and allow the others to be derived from it. If you do choose to explicitly override specific endpoints you are now required to override all of them, which makes the logic simpler and allows for better compile-time checking.
> fix: clean up the support for overriding endpoints

- examples/nodejs/access-control/access-control.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-nodejs/test/unit/auth-client.test.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/client-sdk-web/test/unit/internal/auth-client.test.ts
- packages/common-integration-tests/src/auth-client.ts
- packages/core/src/auth/tokens/disposable-token-scope.ts
- packages/core/src/auth/tokens/disposable-token-scopes.ts
- packages/core/src/auth/tokens/permission-scope.ts
- packages/core/src/auth/tokens/permission-scopes.ts
- packages/core/src/clients/IAuthClient.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/auth/AbstractAuthClient.ts
- packages/core/src/internal/utils/auth.ts
- packages/core/src/messages/responses/generate-api-key.ts
- packages/core/src/messages/responses/refresh-api-key.ts
- packages/core/test/unit/auth/disposable-token-scope.test.ts
- packages/core/test/unit/auth/permission-scope.test.ts
This commit renames `generateAuthToken` and `refreshAuthToken` to `generateApiKey` and `refreshApiKey` respectively. We leave the old names in place, deprecated, to preserve backward compatibility.
> feat: rename `AuthClient.generateAuthToken` to `AuthClient.generateApiKey`

- packages/core/src/auth/credential-provider.ts
- packages/core/test/unit/auth/credential-provider.test.ts
Prior to this commit the options for `CredentialProvider.fromString`
required users to specify an `authToken` option. This commit modifies
the options type so that it supports either `authToken` or `apiKey`.
> feat: support `apiKey` in CredentialProvider.fromString

- packages/common-integration-tests/src/auth-client.ts
FGAC tests were failing on a separate PR but no error message was provided. Replaced instances of `expect` with `expectWithMessage` so that future CI test failures will show the error message.
Also replaced one instance of `generateAuthToken` with `generateApiKey` and changed the FGAC test cache prefix from `fga-` to `js-fga-`.
> chore: use expectWithMessage in FGAC auth integration tests 

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
- packages/core/src/index.ts
Previously, the type `VectorIndexItem` was not exported from sdk-core,
hence could not be re-exported from the SDKs. Because of this,
application code could not make use of the `VectorIndexItem`
type. This PR exports the type accordingly.
> fix: export VectorIndexItem from core and sdks

- packages/client-sdk-nodejs/src/index.ts
The previous commit mistakenly deleted this line, which we re-add.
> fix: re-exports vector response types

- examples/cloudflare-workers/http-api/src/worker.ts
- examples/cloudflare-workers/web-sdk/README.md
- examples/cloudflare-workers/web-sdk/src/worker.ts
Cloudflare reported a bug coming out of the `web-sdk` 
```
Error when setting value in cache! Unknown error has occurred: Cannot read properties of undefined (reading 'trim')
[mf:err] Error: Error setting key key: Unknown error has occurred: Cannot read properties of undefined (reading 'trim')
at MomentoFetcher.set (/Users/gift/Code/demos/client-sdk-javascript/examples/cloudflare-workers/web-sdk/src/worker.ts:58:10)
at async Object.fetch (/Users/gift/Code/demos/client-sdk-javascript/examples/cloudflare-workers/web-sdk/src/worker.ts:104:3)
```
This happens if I do not provide a cache name through the `wrangler.toml` file. Changed examples to throw on missing env vars and updated README to be more clear.
> chore: throw when env vars not set and update readme to be more clear

- packages/client-sdk-nodejs/src/batchutils/batch-functions.ts
- packages/client-sdk-nodejs/src/batchutils/batch-props.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/test/integration/batchutils.test.ts
Addresses [#460](https://github.com/momentohq/dev-eco-issue-tracker/issues/460) by implementing a `BatchUtils` namespace that offers the `batchGet`, `batchSet`, and `batchDelete` functions in the Nodejs SDK.
> feat: add batch get, set, delete functions for nodejs

- packages/client-sdk-nodejs/src/batchutils/batch-functions.ts
Follow up to #916 
The [npm publishing step of the release](https://github.com/momentohq/client-sdk-javascript/actions/runs/6229546809/job/16908230746) for BatchUtils functions failed because of some lint errors 🥲
> fix: lint errors in batch-functions file

- examples/cloudflare-workers/http-api/README.md
- examples/cloudflare-workers/http-api/src/worker.ts
- examples/cloudflare-workers/http-api/wrangler.toml
Made some minor changes to make this example compatible with future Cloudflare integration
- Rename `MOMENTO_REST_ENDPOINT` to `MOMENTO_HTTP_ENDPOINT`
- If `MOMENTO_HTTP_ENDPOINT` doesn't start with `https://`, add it.
- Preserve environment variables added via UI when doing a deploy
> chore: rename env vars and handle endpoints with or without https prefix

- packages/core/src/index.ts
While `ICacheClient` is exported, this interface also depends on the
name `IMomentoCache`, which is not exported. We export that here.
> chore: export IMomentoCache

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
`ALL_VECTOR_METADATA` and `SimilarityMetric` were not re-exported from the
libraries in the previous commit. This commit re-exports them from the sdk libraries.
> chore: re-export vector index request types

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
This re-exports `IMomentoCache` from the top level `index.ts` files. This type is needed to mock the library in third party unit tests.
> chore: re-export IMomentoCache

- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-web/src/internal/leaderboard-data-client.ts
- packages/common-integration-tests/src/leaderboard-client.ts
- packages/core/src/clients/ILeaderboard.ts
- packages/core/src/internal/clients/leaderboard/AbstractLeaderboard.ts
- packages/core/src/internal/clients/leaderboard/ILeaderboardDataClient.ts
- packages/core/src/messages/responses/leaderboard/leaderboard-fetch.ts
- packages/core/src/messages/responses/leaderboard/leaderboard-length.ts
- packages/core/src/utils/cache-call-options.ts
[Ticket #468](https://github.com/momentohq/dev-eco-issue-tracker/issues/468). Addresses feedback we got from the bug bash.
Changes include:
* Removes the `Found` and `NotFound` response classes which were confusing. 
* `Error` is returned when the cache is not found and thus the request failed. 
* `Success` is returned when the cache was found, but does not necessarily mean that requested elements were found (e.g. fetching data from empty or non-existent leaderboards will return length=0 or elements=[] rather than `NotFound` now).
* Removes the `leaderboard` prefixes from the Leaderboard methods.
* E.g. `leaderboardUpsert` --> `upsert`
* Upsert can now accept elements of type `Record<number, number> | Map<number, number>` instead of just `Map<number, number>`.
* `fetchByRank` now requires …
> feat: leaderboard bug bash fixes, updated response classes

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/auth-client.ts
- packages/common-integration-tests/src/auth-client.ts
- packages/core/src/auth/tokens/disposable-token-scope.ts
- packages/core/src/clients/IAuthClient.ts
- packages/core/src/internal/clients/auth/AbstractAuthClient.ts
- packages/core/src/internal/utils/validators.ts
Added token id as optional field (within an optional props) to disposable tokens API. The object `DisposableTokenScope` is encapsulated with all kinds of permission policies that we can provide, and it didn't seem clean to add a `tokenID` field there. Instead, added as a new props for that API.
PR #1 for https://github.com/momentohq/dev-eco-issue-tracker/issues/511
> feat: add token id optional field to disposable tokens

- packages/common-integration-tests/src/leaderboard-client.ts
Each `describe` block creates a new leaderboard and I belatedly realized that each should also delete them when done testing. Also renamed the leaderboards so they all start with `test-leaderboard-` and are hopefully easier to find and manually delete, if necessary.
> chore: delete leaderboard at end of each leaderboard test

- packages/common-integration-tests/src/leaderboard-client.ts
Follow up to #971, but uses a higher order function.
> chore: refactor leaderboard tests to use temporary leaderboards that get deleted

- examples/nodejs/token-vending-machine/README.md
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/handler.ts
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/package-lock.json
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/package.json
Added `tokenId` to TVM examples. I have demonstrated this as a query string parameter as a generic `tokenId` was not making sense but let me know if there's a better way to demonstrate this.
> chore: augment tokenID to token vending machine

- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/common-integration-tests/src/auth-client.ts
- packages/core/src/messages/responses/topic-item.ts
Renaming publisherId to tokenId in SDK as the generateToken API uses this terminology and to be clear to users.
> chore: rename publisherId to tokenId in topic item

- packages/client-sdk-web/src/index.ts
- import and export TopicRole, CacheRole from web-sdk such that they can be consumed from the sdk-web rather than sd-core in the console
> fix: import/export permission roles from web-sdk

- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-web/src/internal/auth-client.ts
We were seeing minimum request latencies of around 10ms from our `generateDisposableTokens` api call. In dotnet, we were seeing requests around 1-2ms. By saving the client as a class var instead of reinstantiating it upon every request, we now see requests inside of lambda take around 1-2ms, which lines up with what we see inside of csharp
> fix: don't reinstatiate new client every auth request

- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/common-integration-tests/src/auth-client.ts
For https://github.com/momentohq/dev-eco-issue-tracker/issues/536
I have been observing failed CIs on this repo since a while and the most common culprits in my observation have been:
- 9/10 times it was the test in this PR that failed. The test essentially checks that the expiration duration of a token  generated at time `x` is within `y-1` and `y+1` where `y` is the expiration time returned by the server after the API call. The window here is small even though it does succeed locally in a loop of 1000 runs. I believe the reason it fails on CIs so frequently is either:
- Event loop contention
- Server side delay that might happen due to several things.
- In one of my failed CIs, the drift was as high as 23 seconds 
```
generate auth token using session token credentials › should succeed …
```
> chore: relax auth test expiration window for CIs under high contention

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/leaderboard.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
Bumped examples release and removed `core` dependency
> chore: removing core dependencies from examples package json

- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/middleware.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/grpc/middlewares-interceptor.ts
Part of the CloudWatch metrics example work (see #970) in order to use requestType as a dimension on the dashboard graphs.
Also exports ExperimentalMetricsLoggingMiddleware at the top-level of the Node.js SDK and adds null and undefined checks for metrics messages (was running into issues with some middleware messages being undefined while working on #970).
Before this change:
>   [2023-10-30T22:05:13.777Z] INFO (Momento: ExperimentalMetricsLoggingMiddleware): 
>   {
>     "numActiveRequestsAtStart":1,
>     "numActiveRequestsAtFinish":1,
>     **"requestType":"MiddlewareMessage"**,
>     "status":0,"startTime":1698703513758,
>     "requestBodyTime":1698703513759,
>     "endTime":1698703513776,
>     "duration":18,
>     "requestSize":13,
>     "responseSize":9,
>     "connectionID":"1"
> …
> fix: experimental metrics middleware should use the grpc message constructor name in emitted metrics instead of MiddlewareMessage

- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
Follow up for https://github.com/momentohq/client-sdk-javascript/pull/995 to web-sdk tests as well
> chore: bump timeout/deadline for web sdk integ tests

- examples/nodejs/lambda-examples/topics-microservice/lib/topics-microservice-stack.ts
The topics example with CDK uses aws-sdk version 3 (`@aws-sdk/*` pattern).  This is excluded by default https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs.BundlingOptions.html#externalmodules 
By specifying `aws-sdk` (version 2) as an external module in the bundling options you're overriding the default external modules which actually causes esbuild to bundle aws-sdk version 3 into the lambda.
This PR removes the incorrect `aws-sdk` (version 2) SDK from external modules so that CDK/esbuild will exclude the version of aws-sdk being used in the project.
cc: CDK fan @allenheltondev 😈
> nodejsfunction excludes aws-sdk by default

- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-csv-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
So that #970 can incorporate MomentoMetricsMiddleware into the metric filters (e.g. `{$.MomentoMetricsMiddleware.status >= 0}`) to avoid clashing with other metrics customers may stream to a log group.
> chore: wrap momento metrics json in `momento` object for cloudwatch metric filters

- packages/client-sdk-nodejs/jest.config.ts
- packages/client-sdk-web/jest.config.ts
Caused a couple of failures [[1](https://github.com/momentohq/client-sdk-javascript/actions/runs/6738387984/job/18317859420), [2](https://github.com/momentohq/client-sdk-javascript/actions/runs/6711852943/job/18240833612)] recently, including failing while publishing the web SDK to npmjs.
Increases the jest timeout so that each test can run for up to 2 minutes instead of 30 seconds. If the timeout should be increased or decreased, let me know.
> chore: increase jest timeout limit

- packages/common-integration-tests/src/auth-client.ts
Addresses [#543](https://github.com/momentohq/dev-eco-issue-tracker/issues/543) and findings in the [Node.js Canary Failures doc](https://www.notion.so/momentohq/Node-js-Canary-Failures-fb81afa7239345deb2051a77e5afd06d).
Changes:
- fix: give more breathing room to flaky refresh auth token test
- audit `expect` statements, use `expectWithMessage` instead.
> fix: flaky auth test, audit expect statements for better logs

- packages/common-integration-tests/jest.config.ts
Saw a recent failure in the sdk canary logs due to the 30 second jest timeout. 
Realized I'd missed one jest config file to update when doing #1003 to address flaky tests.
> fix: extend jest timeout for common integration tests package

- scripts/build-package.sh
`npm run format` can modify the files in a pr, but does not commit this modification. When we go to publish the package, if the lint check is not passing then the publish will fail. We should commit these lint fixes
> fix: don't run npm run format during ci

- examples/nodejs/token-vending-machine/README.md
- examples/nodejs/token-vending-machine/infrastructure/package.json
This commit adds a `deploy` target to the token vending machine
and updates the README to use that for deploying instead of `cdk`.
The main motivation here is to automate the `npm install` step for
the lambda project, to prevent users from accidentally skipping it
and running into an error or deploying the lambda with an outdated
version of the dependencies.
> chore: add `deploy` target for TVM to make it easier to deploy

- examples/nodejs/cache/.prettierrc.json
- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/rate-limiter/.eslintrc.json
- examples/nodejs/rate-limiter/.prettierrc.json
- examples/nodejs/rate-limiter/doc-examples-files/doc-examples.ts
- examples/nodejs/rate-limiter/momento-rate-limiter.ts
- examples/nodejs/rate-limiter/package-lock.json
- examples/nodejs/rate-limiter/package.json
- examples/nodejs/rate-limiter/worker.ts
- packages/client-sdk-nodejs/.eslintrc.json
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
On every pr we see a bunch of these eslint warnings, which causes noise and makes the pr harder to grok. This commit fixes all these eslint warnings so that they will no longer appear on every pr
> chore: cleanup code causing warning errors on prs

- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/messages/responses/vector/vector-search.ts
To align with the `scoreThreshold` option in `search`, and for
clarity in that the search hits are not ordered by `distance` (which
is lower or better), but by `score` (which could be higher or better,
or a blend of multiple things), we rename the `distance` property to
`score`.
> refactor: rename mvi searchhit property from distance to score

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
Updates the MVI Node.js and Web doc examples for the latest changes to list indexes. Bumps the dependencies in the two projects and updates list indexes response printing.
> chore: update mvi examples

- .github/workflows/on-push-to-release-branch.yml
Issue: https://github.com/momentohq/dev-eco-issue-tracker/issues/560
[GitHub recommends](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) using the `$GITHUB_OUTPUT` environment variable instead.
> fix: github deprecated set-output command

- scripts/update-package-versions.sh
Run build-and-test-package.sh for each package being released instead of manually calling the build, lint, and test commands. This builds the release packages in the same way that pr packages are built.
Part of https://github.com/momentohq/dev-eco-issue-tracker/issues/546
Both scripts ran `npm run lint` already, so I don't know how the release job was failing on lint if a pr didn't, but this makes them use the same code at least.
> chore: build in the same way on PRs and releases

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
Updates generated types in Web SDK and Node JS packages and consumes the name change in `SearchHit` from `distance` to `score`.
> chore: update generated types and consume searchhit score change

- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-web/.eslintrc.json
- packages/client-sdk-web/src/internal/cache-control-client.ts
- packages/common-integration-tests/.eslintrc.json
- packages/core/.eslintrc.json
I noticed there were some places in our control plane clients where we where logging `this.logger.info` and other places where we were logging `this.logger.debug`. This commit just consolidates these. Also adds new eslint rule to ignore unused variables that start with `_`
> chore: code cleanup, standardize logging

- examples/nodejs/cache/doc-example-files/collection-ttl.ts
- examples/nodejs/cache/package.json
This is based on user feedback that our docs didn't provide enough
clarity around CollectionTtl. In a subsequent PR we will consume
these examples from the docs.
> chore: add example snippets for CollectionTTL

- packages/core/test/unit/utils/expiration.test.ts
`(new Date()).getSeconds()` returns the seconds of the date object. So can be any number between 0 and 59. `Date.now()` returns the epoch milliseconds. If we happened to get unlucky when the test ran and the seconds were at 0, then when we add 60 seconds to the date object, then seconds would still be 0, and our test would fail since our `expiresIn` would not expire
> fix: expiration.test.ts date.now()

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
Include doc API snippets in Web and Node.js for `searchAndFetchVectors`.
In the Node.js project, there was an extraneous dependency on sdk-core, which we remove.
> chore: update mvi api snippets to add searchAndFetchVectors

- .github/workflows/build.yml
- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-control-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-control-client.ts
Update MVI list and create index backends for latest protos. The developer-facing API remains the same; this is only an internal update.
> chore: update mvi control plane backend for latest create and list indexes protos

- packages/common-integration-tests/src/vector-control-plane.ts
- packages/core/src/internal/clients/vector/IVectorIndexControlClient.ts
- packages/core/src/messages/responses/vector/list-vector-indexes.ts
- packages/core/src/messages/vector-index-info.ts
- packages/core/test/unit/messages/responses/vector-index-info.test.ts
- packages/core/test/unit/messages/responses/vector/list-vector-indexes.test.ts
This adds sensible toString implementations for
VectorSimilarityMetric, VectorIndexInfo, and
ListVectorIndexes.Success.
We also update the integration tests in light of this and add unit
tests for the to string and equals implementations on the messages.
> chore: improve toString for IndexInfo and members

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/topic-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/src/topic-client.ts
We are seeing issues installing the lastest nodejs `1.50.4` sdk. On main, when building the nodejs sdk, the dist output looks like
```
dist
├── client-sdk-web
│   ├── package.json
│   ├── src
│   └── test
└── core
└── src
```
It is expecting 
```
dist/src/index.js
```
This is resulting in an error `Unable to resolve path to module '@gomomento/sdk'` when trying to install the sdk.
It looks like this has to do with some of our imports for the webhooks client coming from `../core/...` vs `@gomoment-core/dist/...`. 
I have tested this change locally on my box, `npm pack` the sdks, installing them in examples, and making sure they will work. I will fast follow this with a pr that will add some steps to our build to ensure that the `dist` folder has the correct folder structure. But I want to …
> fix: import structure so dist folder has correct folder heirarchy

- packages/core/src/messages/vector-index-info.ts
- packages/core/test/unit/messages/responses/vector-index-info.test.ts
- packages/core/test/unit/messages/responses/vector/list-vector-indexes.test.ts
We add quoting on the to VectorIndexInfo string fields on `toString`
for clarity.
> chore: tweak vector index info to string to quote string fields

- .github/workflows/build.yml
- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
follow-up to https://github.com/momentohq/client-sdk-javascript/pull/1045
Makes sure that nodejs and web sdk can be packaged and installed in our example repos, ensuring that the packing is correct
> feat: test and verify package on build

- packages/common-integration-tests/src/auth-client.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/create-delete-list-cache.ts
Inside of github actions, the env var `CI` is always set to true
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
We can use this to key off of, and have a certain subset of integration tests only run in the CI environment, such as ones that verify limits against a cache
> fix: don't validate limits outside of CI

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
Corrected the logger statements for sortedSetPutElements. Had been showing up as an error in a customer's logs
> fix: correct number of arguments for sortedSetPutElements logger statements

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/clients/IVectorIndexClient.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/vector/AbstractVectorIndexClient.ts
- packages/core/src/internal/clients/vector/IVectorIndexDataClient.ts
- packages/core/src/messages/responses/vector/index.ts
- packages/core/src/messages/responses/vector/vector-get-item-batch.ts
- packages/core/src/messages/responses/vector/vector-get-item-metadata-batch.ts
- packages/core/src/messages/vector-index.ts
Implements MVI `get item batch` and `get item metadata batch`, adds tests, and extracts `VectorIndexMetadata` to separate type.
> feat: add mvi methods for get item (metadata)? batch

- .github/workflows/update-example-deps.yml
This is the first step of replacing the dependabot functionality;
for now all this does is run the script. Will add more commits
to make it file a PR once we ensure this is working.
> chore: add scheduled job to update momento deps in all examples

- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/messages/responses/vector/vector-get-item-batch.ts
- packages/core/src/messages/responses/vector/vector-get-item-metadata-batch.ts
Consistent with the cache terminology, we use the noun `values` to
access the `get item batch` and `get item metadata batch` items.
> refactor: use `values` noun for get item* consistent w/cache usage

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
When implementing these 2 new methods, I forgot to export their return types. This pr just adds these as some more exports in `index.ts`
> fix: correctly export get/rotate webhook secret response types

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
Adds examples to be consumed by our docs for webhooks. There are 2 more webhooks api that I want to add, but I need to merge and release [this](https://github.com/momentohq/client-sdk-javascript/pull/1072) pr first to be able to import their return types
> chore: add examples to docs for webhooks apis

- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/vector-control-plane.ts
- packages/common-integration-tests/src/vector-data-plane.ts
Because we are seeing indexes leak in integration tests, we
hypothesize a particular integration test or tests may be at fault. To
identify these, we add a suffix to the test name that identifies each
test case.
I feel this is a good practice to adopt going forward
across the board.
> test: add suffix to identify integration test index names

- packages/core/src/messages/responses/vector/list-vector-indexes.ts
We have adopted a pattern where users can call accessors on the
response base class to avoid an instanceof guard. That is, suppose a
user calls `client.listIndexes()`. This returns a
`ListVectorIndexes.Response` class, which will either be a `Success`
or `Error`. A user should then use `instanceof` to check the appropriate
subtype.
In order to simplify access we move the accessor to the base class and
do an instanceof check there. In the event the response is not a
success we return undefined.
> chore: use default accessor in mvi list indexes response base

- examples/nodejs/cache/doc-example-files/config-and-error-handling.ts
The combination of the new `.value()` accessors and the `WithThrowOnErrors`
config allows users to write code that doesn't do any `instanceof` checks.
That is probably the more idiomatic combination for cases where users are
doing `ThrowOnError`. This commit updates the ThrowOnError example code
to use `.value()`, accordingly.
> chore: use the `.value()` syntax in the ThrowOnErrors example

- examples/nodejs/cache/package-lock.json
- examples/nodejs/cache/package.json
- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/cache/package-lock.json
- examples/web/cache/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
Add example snippets for MVI `countItems` in both the Web and Node.js vector index examples.
Because the cache examples sdk dependencies were out of date for latest leaderboard changes, we also updated those.
> chore: update example snippets for mvi count items

- packages/client-sdk-nodejs/src/config/leaderboard-configuration.ts
- packages/client-sdk-nodejs/src/config/leaderboard-configurations.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/preview-leaderboard-client.ts
adds a couple more config options to leaderboard clients, now able to set a different client timeout (in milliseconds) and add middleware (such as the Momento metrics middleware)
can now enable metrics middleware and set a different timeout like so:
```
const loggerFactory = new DefaultMomentoLoggerFactory(DefaultMomentoLoggerLevel.TRACE);
const client = new PreviewLeaderboardClient({
configuration: LeaderboardConfigurations.Laptop.v1(loggerFactory).withClientTimeoutMillis(2000).withMiddlewares([
new ExperimentalMetricsLoggingMiddleware(loggerFactory),
]),
credentialProvider: CredentialProvider.fromEnvironmentVariable({
environmentVariableName: 'MOMENTO_API_KEY',
}),
});
```
> feat: add withClientTimeoutMillis and withMiddlewares to Leaderboard configs

- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/clients/IVectorIndexClient.ts
- packages/core/src/index.ts
- packages/core/src/messages/vector-index-filters.ts
Adds filter expression data types and implementation for `search` and
`searchAndFetchVectors`. Includes search filters for equality checks and logical expressions. A followup PR will include the exhaustive set of comparison operators.
> feat: implement mvi search filters

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/clients/IVectorIndexClient.ts
In preparation for a broader usage of filters, which could be a list
of ids or a filter expression, we rename the `filterExpression`
argument to `filter`.
> refactor: mvi filter expression rename

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
In the previous release we exported the vector filter names from core
but not from the SDKs. This PR corrects that.
> chore: export vector filter names from sdks

- packages/client-sdk-nodejs/src/internal/grpc/middlewares-interceptor.ts
Check connection state inside the if-block to avoid work during successful responses
> fix: move check connection state inside the if block

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/nodejs/vector-index/package-lock.json
- examples/nodejs/vector-index/package.json
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
- examples/web/vector-index/package-lock.json
- examples/web/vector-index/package.json
This PR adds an example snippet demonstrating vector index filter expressions. Because each filter expression type is (in my opinion) straigthforward on its own, I add a holistic example showing many expressions over a single metadata schema.
> chore: add mvi example snippets for filter expressions

- examples/nodejs/vector-index/doc-example-files/doc-examples-nodejs-apis.ts
- examples/web/vector-index/doc-example-files/doc-examples-web-apis.ts
In the MVI filter expression example we have a blurb about the example
data schema. Because we are moving that to the docs page, we are
deleting it from the example.
> chore: remove mvi filter expression schema mention in snippets

- packages/client-sdk-nodejs/src/config/leaderboard-configurations.ts
- packages/client-sdk-nodejs/src/config/vector-index-configurations.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/grpc/grpc-channel-options.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
Prior to this commit we had several different places in the code where
we were manually constructing an instance of grpc-js's `ChannelOptions`.
This commit creates a helper function to consolidate the construction
in a single spot; we accept an instance of our `GrpcConfiguraion` as input.
As we add support for more of the different grpc settings over time, this
will become increasingly more important.
> chore: DRY up nodejs grpc channel configuration

- packages/client-sdk-nodejs/src/config/transport/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/transport-strategy.ts
- packages/client-sdk-nodejs/src/internal/grpc/grpc-channel-options.ts
Prior to this commit, we were not explicitly setting the max size for grpc requests and responses. The default was 4mb, which meant that if a user had requested a limit increase to support 5mb item sizes, the SDK was not actually capable of serving those items back to them.
This commit adds configuration options to support setting different values for the max request and response size, and sets the defaults to 5mb to support those customers.
> fix: add support for item sizes up to 5 mb.

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
We are in the process of migrating MVI delete item batch, get item batch, and get item metadata batch to use a filter expression to select items to delete (get) as opposed to a list of id's. For convenience, we will still allow users to select items with a list of id's from the top level methods. This PR migrates the backend.
As part of the migration we are also moving away from the hit/miss pattern for get item batch and get item metadata batch response messages. While the hit/miss pattern made sense for when we only selected items by id, it no longer makes sense for when a user supplies a general filter expression. What's more, previously when we read the hit/miss responses, we built an object containing only the hits, so the distinction wasn't as important.
In future PRs we will add …
> refactor: use mvi filter fields for get/delete items

- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/core/src/clients/IVectorIndexClient.ts
- packages/core/src/internal/clients/vector/AbstractVectorIndexClient.ts
- packages/core/src/internal/clients/vector/IVectorIndexDataClient.ts
To standardize how we select items in get item batch, get item metadata batch, and delete item batch, we use the term filter in methods, whether selecting by ids or filter expression.
> refactor: rename mvi parameter ids to filter in get/delete

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
gRPC 1.9.14 release had a couple fixes relevant to issues we were seeing with reconnections:
- https://github.com/grpc/grpc-node/issues/2620
- https://github.com/grpc/grpc-node/pull/2643
- https://github.com/grpc/grpc-node/pull/2644
> chore: bump gRPC versions

- packages/client-sdk-nodejs/src/internal/vector-index-data-client.ts
- packages/client-sdk-web/src/internal/vector-index-data-client.ts
- packages/common-integration-tests/src/vector-data-plane.ts
- packages/core/src/clients/IVectorIndexClient.ts
- packages/core/src/internal/clients/vector/AbstractVectorIndexClient.ts
- packages/core/src/internal/clients/vector/IVectorIndexDataClient.ts
Adds an overload MVI `deleteItemBatch` to allow users to delete items by not just a list of ids, but also a more general filter expression. We maintain the option of providing a list of ids for convenience. This PR adds integration tests and updates the documentation.
> feat: add mvi delete by filter overload

- packages/client-sdk-nodejs/jest.config.ts
- packages/client-sdk-web/jest.config.ts
Saw a lot of jest test timeouts while collecting test failure data over the last couple of weeks, particularly in the web SDK. Doubled the timeout for both just in case
> chore: increase jest test timeout to reduce flaky tests

- packages/client-sdk-nodejs/jest.config.ts
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/jest.config.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
Was still seeing occasional test failures related to jest test timeouts, mostly for vector tests in the web sdk, but doubling the timeout again here in both just in case. 
Also increasing the cache client timeout by 30 seconds after seeing timeout errors from different tests, figured there might be enough tests added recently that increasing the timeout a bit might be worth a shot.
> chore: increase jest and test cache client timeouts

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/test/integration/shared/batch-get-set.test.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/client-sdk-web/test/integration/shared/batch-get-set.test.ts
- packages/common-integration-tests/src/batch-get-set.ts
- packages/common-integration-tests/src/index.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
- packages/core/src/messages/responses/cache-batch-get.ts
- packages/core/src/messages/responses/cache-batch-set.ts
Adds batch get and set APIs for [#674](https://github.com/momentohq/dev-eco-issue-tracker/issues/674)
Note: the streaming APIs use a different set of interceptors, this issue is still open: https://github.com/momentohq/client-sdk-javascript/issues/349 
Another note: this PR doesn't remove the [nodejs batchutils functions](https://github.com/momentohq/client-sdk-javascript/tree/main/packages/client-sdk-nodejs/src/batchutils)
> feat: setBatch and getBatch

- packages/client-sdk-nodejs/src/internal/grpc/middlewares-interceptor.ts
This commit will allow us to look at the log for the gRPC connection status when a deadline/timeout is observed
> chore: update log level during timeout to warn

- packages/common-integration-tests/src/create-delete-list-cache.ts
We have a test that makes assertions about the cache limits configuration,
both to provide test coverage of the control plane API and to ensure that
we have a sufficient, uniform configuration across the canary environments.
We are currently in the process of raising the limits to allow more parallelization
of tests. This PR temporarily relaxes the constraint for the TPS limit from
equality to `>=` to allow us some flexibility until we know the final value.
> chore: temporarily allow >= for expected throttling limits

- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
I tested the set and getItemTtl in our nodejs sdk. I used default ttl to be 1 day and then set a key in cache passing the ttl to be 3 days. The getItemTtl returns 3 days.
Code ref:
```
const momento = await CacheClient.create({
configuration: Configurations.InRegion.Default.v1(),
credentialProvider: CredentialProvider.fromEnvironmentVariable({
environmentVariableName: 'MOMENTO_API_KEY',
}),
defaultTtlSeconds: 86400,
});
const setResponse = await momento.set('test-js', 'test-key-2', 'test-value-2', {
ttl: 259200
});
if (setResponse instanceof CacheSet.Success) {
console.log('Key stored successfully!');
} else {
console.log(`Error setting key: ${setResponse.toString()}`);
}
const itemTtlResponse = await momento.itemGetTtl('test-js', 'test-key-2');
if (itemTtlResponse instanceof …
```
> fix: add runtime check for JS in set api

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-logging-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/middleware.ts
- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/preview-leaderboard-client.ts
- packages/client-sdk-nodejs/test/integration/cache-client-close.test.ts
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/src/internal/cache-control-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/leaderboard-data-client.ts
- packages/client-sdk-web/src/preview-leaderboard-client.ts
- packages/common-integration-tests/src/create-delete-list-cache.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/ILeaderboardClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IControlClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
- packages/core/src/internal/clients/leaderboard/ILeaderboardDataClient.ts
Adds close method to cache clients and middlewares. This allows for proper cleanup of resources, and also doesn't leave any background intervals lurking.
> feat: add close method to clients

- packages/common-integration-tests/src/create-delete-list-cache.ts
- packages/core/src/auth/credential-provider.ts
- packages/core/src/internal/utils/auth.ts
- packages/core/test/unit/auth/credential-provider.test.ts
Although the Web SDK contains logic to automatically prefix its endpoints with `web.` when computing them from an API key, it declines to apply that logic to endpoint overrides passed in by the user. This is problematic when using a `BaseEndpointOverride`, where endpoint URIs are dynamically computed from a common base string. This commit extends the `BaseEndpointOverride` to include an `endpointPrefix`, allowing users to supply a prefix top be prepended to each computed URI.
Similar to #1165 this PR relaxes a test assertion about throttling limits. This is intended to be a temporary change while the limits in the test environment are in flux.
> chore: add endpoint prefix

- packages/client-sdk-nodejs/test/integration/large-messages.test.ts
Skipping this test so that canaries don't fail over the weekend while we wait for a service deployment to get the 5mb message size limit fix out to all cells.
> chore: skip 5mb test until service changes deploy

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
Clearvector log had an eager connection failure that truncated the stack trace :( 
CurrentState 1 indicates `CONNECTING` and it took 40 seconds for successful requests to show up.
```
| 1709840715443 | 2024-03-07T19:45:15.443Z e614536c-623d-5393-be95-0d087951900d ERROR [2024-03-07T19:45:15.442Z] ERROR (Momento: _CacheDataClient): Unable to connect to Momento: Error. currentState: 1 :               Please contact Momento if this persists.
```
> chore: expand eager connection failure log

- packages/client-sdk-nodejs/src/config/middleware/experimental-active-request-count-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-event-loop-perf-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-metrics-logging-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-middleware-factory.ts
- packages/client-sdk-nodejs/src/config/middleware/impl/experimental-metrics-middleware.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/test/integration/cache-client-close.test.ts
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
This PR extracts the event loop metrics from the metrics logging middleware. The metrics logging middleware is per request and can take a toll on customer's CW bills. We'd want to sometimes measure event loop alone without needing request level metrics so a separate middleware is better for that. A factory method is provided for different options to enable the kind of metrics the user wants, to avoid initializing the middleware for each one.
Usage:
```
const middlewares: Middleware[] = MiddlewareFactory.createMetricsMiddleware(middlewaresExampleloggerFactory, {
eventLoopMetrics: true,
activeRequestCountMetrics: true,
perRequestMetrics: true,
});
const middlewaresExampleClient = await CacheClient.create({
configuration: Configurations.Laptop.v1(middlewaresExampleloggerFactory) …
```
> chore: decouple event loop metrics into its own middleware

- packages/client-sdk-nodejs/src/config/middleware/experimental-event-loop-perf-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-garbage-collection-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-middleware-factory.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/test/integration/cache-client-close.test.ts
This PR adds a middleware to emit GC events. It subscriber's to node's built-in performance hook for garbage collection. The data emitted here is [similar](https://nodejs.org/en/learn/diagnostics/memory/using-gc-traces) to what we'd get through `--trace-gc` on a nodejs process with more control. The cadence is dictated by the the hook's observer, so we filter out major GC events  to log through filter `NODE_PERFORMANCE_GC_MAJOR`. This [SO post](https://stackoverflow.com/questions/74165486/gc-operation-types-in-nodejs) is the closest to documentation provided for these flags unfortunately, and the [official docs](https://nodejs.org/docs/latest-v16.x/api/perf_hooks.html#performanceentryflags) don't describe it properly. These logs however were printed 5-6 times in a 1 minute run of the …
> feat: add middleware for emitting GC events

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
This commit just makes some minor cleanups to the logic in the
example code for topic subscriptions. In particular:
* Change the wording of the messages a bit so that it's clear that
the `OnItem` represents when a message was received rather than
published.
* Change the `setTimeout` call so that we are awaiting it to ensure
that the published message has time to get recieved on the
subscription. Previously this call to setTimeout was not being
awaited, so we just moved on to the subscription cancellation
immediately and then logged the waiting message 2 seconds later :)
> fix: cleanups to topic subscription example code

- packages/client-sdk-nodejs/test/integration/large-messages.test.ts
Unskipping this test now that canary cells have the 5mb fix
> chore: unskip 5mb test

- packages/client-sdk-nodejs/src/config/middleware/experimental-garbage-collection-middleware.ts
Adding another flag to GC metrics as on raider logs we didn't see any GC log during the 30-60 second prior to OOMs. The v8 engine automatically dumps a couple before going OOM but that doesn't help much as its only the last bit of GC events. Adding another flag to give a shot as this flag aims to incrementally log GC events as the process is approaching close to max memory but don't have a lot of hope.
```
2024-03-15T16:42:33.194Z [2024-03-15T16:42:33.194Z] INFO (Momento: ExperimentalEventLoopPerformanceMetricsMiddleware): {"eventLoopUtilization":0.11524289698329374,"eventLoopDelayMean":20044800,"eventLoopDelayMin":19070976,"eventLoopDelayP50":20070399,"eventLoopDelayP75":20070399,"eventLoopDelayP90":20316159,"eventLoopDelayP95":20660223,"eventLoopDelayP99":20742143,"eventLoopDelayMax":207 …
```
> chore: add incremental gc metrics to middleware

- packages/common-integration-tests/src/auth-client.ts
Updated the sleep to 1.5 sec instead of 1 sec to give little extra buffer.
We have also updated the error code refresh token api with expired token, to make sure the changes flow through smoothly, checking for error code to be one of the old or new one.
Verified that the tests are passing with this change:
> fix: Updated the sleep time for auth token expiry

- packages/common-integration-tests/src/auth-client.ts
Tests seem flaky so updating the sleep to be 3 sec
> fix: update sleep time for auth token expiry apis

- .gitignore
- .vscode/client-sdk-javascript.code-workspace
Adds a recommended workspace file for vs code users. This allows
developers to view all the main projects in the repo in one view, with
the node modules resolution working as if each folder were opened
independently. See
https://code.visualstudio.com/docs/editor/multi-root-workspaces
> chore: add vscode workspace config

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/configuration.ts
- packages/client-sdk-web/src/cache-client.ts
In order to read the configuration from an already instantiated cache
client externally, we add configuration getters to the cache clients.
> chore: add configuration getters to cache clients

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
Rishti had pointed out the incorrect docstrings a little while ago, and I noticed the missing dev docs snippets for KeyExists and KeysExist while implementing them in the Rust SDK.
> chore: add missing KeyExists and KeysExist docs snippets and correct docstrings

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/transport/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/transport-strategy.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/core/src/internal/utils/index.ts
- packages/core/src/internal/utils/semaphore.ts
- packages/core/test/unit/utils/semaphore.test.ts
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/739
* Adds semaphore class in `core` package and exposes `concurrentRequestsLimit` as a grpc config option in the Node.js sdk. (Can implement in web sdk too if useful)
* Creates a semaphore in the CacheClient that caps the number of concurrent requests across all of the data clients. Had to wrap each API `send*` request in a `try-finally` block to acquire and release the semaphore.
* Adds unit tests for the semaphore class in the `core` package
Locally verified that given a `Promise.all` with 100 get requests with concurrency limit set to 10, there are only a max of 10 active requests at once. Logs snippet:
```
[2024-04-03T20:41:49.386Z] INFO (Momento: ExperimentalMetricsLoggingMiddleware): …
```
> feat: add max concurrent request limit config option

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
Previously the error types on various conditional set operations were
`CacheGet.Error` instead of the appropriate type.
> fix: correct error types on various conditional set operations

- packages/core/src/internal/utils/semaphore.ts
Previously we used unknown and any types for the sempahore internal
promise resolve/error types. We can use more specific ones to avoid
warnings on GH.
> fix: use specific semaphore resolve/err types

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/transport/transport-strategy.ts
- packages/client-sdk-nodejs/test/unit/cache-client.test.ts
- packages/core/src/internal/utils/validators.ts
Follow up to #1209, addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/739
Realized WithConcurrentRequestsLimit was missing from the TransportStrategy interface. Should now be publicly accessible and usable.
Added validator to ensure limit is strictly positive. Added unit tests to confirm.
> fix: expose WithConcurrentRequestsLimit on TransportStrategy interface, add validator and test

- packages/client-sdk-nodejs-compression/test/integration/compression.test.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/utils/cache-call-options.ts
Adds compression support for dictionaries, specifically on `dictionarySetField`, `dictionarySetFields`, `dictionaryGetField`, `dictionaryGetFields`, and `dictionaryFetch`. We add integration tests on the compression library and refactor the library as well to handle comparing `Uint8Array`s better.
In a future PR we ought to refactor the backend to reduce code duplication. With the integration tests in place now, that should be less risky.
> feat: add compression for dictionaries

- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/batch-get-set.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/785
Renames objects for better consistency with the other cache response objects.
Will follow-up to update example code after this change is released.
> feat: rename GetBatch and SetBatch response objects to CacheGetBatch and CacheSetBatch

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/get-set-delete.ts
Fixes a bug in how ttl is set in `increment`: https://github.com/momentohq/client-sdk-javascript/issues/1158
> fix: small bug fix in increment ttl

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/transport/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/transport-strategy.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/test/unit/cache-client.test.ts
- packages/core/src/internal/utils/validators.ts
Users should opt-in to setting the max concurrent requests limit. The default behavior of the SDK should remain the same if the limit is not set (locally confirmed this). 
Renamed from ConcurrentRequestsLimit to MaxConcurrentRequests.
Created a higher order function to apply the semaphore (if max concurrent request limit is set).
> feat: make max concurrent requests an opt-in config, remove default setting

- examples/nodejs/get-set-batch-perf-test/package-lock.json
- examples/nodejs/get-set-batch-perf-test/package.json
- examples/nodejs/get-set-batch-perf-test/perf-test.ts
- examples/nodejs/get-set-batch-perf-test/utils/cache.ts
- examples/nodejs/get-set-batch-perf-test/utils/perf-test-utils.ts
This commit does the following:
* Updates our typescript/eslint/etc. dependencies due to some weird TS errors that were
popping up. There is now a minimum node version of 18 to run this project.
* Run all the tests twice, once with a cache client with MaxConcurrentRequests enabled,
and once with it disabled. This will allow us to compare the numbers for the async
runs with both permutations of the MaxConcurrentRequests setting.
> chore: tweaks to getbatch perf tests to account for new max concurrent requests setting

- packages/client-sdk-nodejs/src/cache-client.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-active-request-count-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/experimental-event-loop-perf-middleware.ts
- packages/client-sdk-nodejs/src/config/middleware/middleware.ts
- packages/client-sdk-nodejs/src/preview-leaderboard-client.ts
- packages/client-sdk-nodejs/test/integration/cache-client-close.test.ts
This works around an issue that left background logging tasks from the middleware running, preventing jest from exiting. This is a workaround until a better solution for notifying the middlewares that they should start logging after successful client instantaiation can be implemented.
> fix: instantiate middleware after cred provider

- packages/client-sdk-nodejs/README.md
- packages/client-sdk-nodejs/README.template.md
- packages/client-sdk-web/README.md
- packages/client-sdk-web/README.template.md
Due to the nature of mono repos, relative path pointing to examples will break in README. Updated to absolute paths instead for examples on README.
> chore: fix readme to point to correct examples dir

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/batch-get-set.ts
- packages/common-integration-tests/src/dictionary.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
- packages/core/src/messages/responses/cache-batch-get.ts
- packages/core/src/messages/responses/cache-dictionary-fetch.ts
- packages/core/src/messages/responses/cache-dictionary-get-fields.ts
- packages/core/src/messages/responses/cache-sorted-set-get-scores.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/set-batch-item.ts
Addresses https://github.com/momentohq/client-sdk-javascript/issues/1250
Updated by Chris:
In addition to the adding per-item TTL, this PR does the following:
* Adds more test coverage for the different value accessors for the
GetBatch response, because some of them weren't being tested, and
there was a bug in the web SDK implementations.
* Fix the web SDK implementations so that the `valueRecord*` and
`valueMap*` accessors work properly.
* Remove various accessors for GetBatch and Dictionaries that attempted
to return `Map<Uint8Array, *>`. This was done after spending a lot
of time trying to write tests to cover these accessors in GetBatch
and seeing how easy it is to make a very minor mistake that results
in the inability to access a value in the Map. For example, if you
try to index …
> feat: allow setting ttl per item in setBatch

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/keys-exist.ts
- packages/core/src/messages/responses/cache-keys-exist.ts
We add a record accessor for keys exist to be in line with the .NET
and Rust SDKs.
The record maps from the key to a boolean indicating whether the key
exists in the cache or not.
> chore: add record accessor for keys exist response

- examples/nodejs/cache/doc-example-files/patterns.ts
adds `patterns.ts` example file to be consumed downstream in dev docs
> fix: add javascript patterns examples files

- .github/workflows/build.yml
Ended up not re-adding 14 because it no longer works on github. We should add 20 though.
> chore: add node 20 to examples, and re-add node 14

- .github/workflows/build.yml
- .github/workflows/on-push-to-main-branch.yml
- examples/nodejs/aws/README.template.md
- examples/nodejs/aws/lambda-examples/README.template.md
- examples/nodejs/aws/lambda-examples/advanced-compression/.gitignore
- examples/nodejs/aws/lambda-examples/advanced-compression/README.template.md
- examples/nodejs/aws/lambda-examples/advanced-compression/esbuild.ts
- examples/nodejs/aws/lambda-examples/advanced-compression/nodemon.json
- examples/nodejs/aws/lambda-examples/advanced-compression/package-lock.json
- examples/nodejs/aws/lambda-examples/advanced-compression/package.json
- examples/nodejs/aws/lambda-examples/advanced-compression/postbuild.ts
- examples/nodejs/aws/lambda-examples/advanced-compression/src/index.ts
- examples/nodejs/aws/lambda-examples/advanced-compression/template.yaml
- examples/nodejs/aws/lambda-examples/advanced-compression/tsconfig.json
This commit adds an advanced compression example, which illustrates
how to package your code for use in AWS lambda when you are using
the `@gomomento/sdk-nodejs-compression-zstd` library. It walks
through the steps required to make sure that you package the
correct binary for the target platform, even if you are doing
the build from a different platform.
> chore: add example for using zstd compression in nodejs lambda

- README.template.md
- examples/nodejs/compression-zstd/README.template.md
- examples/nodejs/compression/doc-example-files/doc-examples-js-apis.ts
This just tweaks the wording and links in a few more places now that
we have the zstd lambda example working.
> chore: hopefully final few tweaks for compression docs/examples

- .github/workflows/build.yml
Only the `Build` job gets cancelled after 4 minutes when using ubuntu 24, so trying to revert that one to macos-latest for now
> chore: run cache tests on macos-latest instead of ubuntu 24

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-nodejs/src/internal/ping-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/internal/webhook-client.ts
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/integration-setup.ts
- packages/client-sdk-web/test/unit/utils/web-client-utils.test.ts
- packages/core/src/auth/credential-provider.ts
- packages/core/src/internal/utils/auth.ts
- packages/core/test/unit/auth/credential-provider.test.ts
Allows a user to specify whether each overridden endpoint should use TLS or not. 
~~Also changes `StringMomentoTokenProvider` to detect whether `:443` is contained in the endpoint to determine secure vs insecure when given no overrides.~~
Removed the auto-detect port `443` because it turns out endpoints like `cache.etc.etc.momentohq.com` don't contain the port number.
> feat: add withMomentoLocal and option to connect without TLS to CredentialProvider

- .github/workflows/build.yml
Follow up to https://github.com/momentohq/client-sdk-javascript/pull/1296
Looks like the [issue](https://github.com/actions/runner-images/issues/9959) was resolved yesterday!
> chore: switch back to using Ubuntu 24 for integration tests

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
Error messages regarding connection state now look like:
```
ERROR (Momento: CacheDataClient): Unable to connect to Momento: Unexpected connection state: SHUTDOWN., oldState: IDLE
Please contact Momento if this persists.
```
> chore: improve log message for unexpected connection state

- packages/client-sdk-nodejs/test/integration/large-messages.test.ts
This test has been failing regularly in one of the canaries and we're not sure why, it only says that it's been receiving `Miss` instead of `Hit`.
This PR adds a uuid to the key to make sure it's unique, increases the ttl to 2000 seconds in the unlikely case the 5mb item has been ttl-ing out of the cache, calls `itemGetTtl` after `set` to sanity check, and adds the ttl value and a timestamp to the `expect` messages to try to get more info from the logs when it fails in the canary.
> chore: add more logs and safeguards around 5mb test

- packages/client-sdk-nodejs/test/integration/large-messages.test.ts
Ensures that a log statement will be printed when the 5mb test runs to sanity check that the ttl is correct.
Example:
```
Expecting ttl for key js-5mb-key-808a9a4b-b800-412c-9cca-0f1a72c826f0 to be positive, received: 1999868
```
> chore: sanity check ttl after setting 5mb item in test

- examples/cloudflare-workers/http-api/src/worker.ts
chore: In cloudflare example, ensure endpoints starting with http:// are correctly prefixed with https://
Previously, endpoints starting with http:// were prefixed with https://, which could lead to incorrect URL formation. This commit adjusts the prefix process to handle these cases properly.
> chore: handle http endpoint url

- .github/workflows/build.yml
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/core/src/messages/responses/cache-dictionary-fetch.ts
- packages/core/src/messages/responses/cache-dictionary-get-field.ts
- packages/core/src/messages/responses/cache-dictionary-get-fields.ts
- packages/core/src/messages/responses/cache-dictionary-increment.ts
- packages/core/src/messages/responses/cache-dictionary-length.ts
- packages/core/src/messages/responses/cache-dictionary-remove-field.ts
- packages/core/src/messages/responses/cache-dictionary-remove-fields.ts
- packages/core/src/messages/responses/cache-dictionary-set-field.ts
- packages/core/src/messages/responses/cache-dictionary-set-fields.ts
- packages/core/src/messages/responses/cache-set-add-element.ts
- packages/core/src/messages/responses/cache-set-add-elements.ts
- packages/core/src/messages/responses/cache-set-fetch.ts
- packages/core/src/messages/responses/cache-set-remove-element.ts
- packages/core/src/messages/responses/cache-set-remove-elements.ts
- packages/core/src/messages/responses/cache-set-sample.ts
- packages/core/src/messages/responses/cache-set.ts
- packages/core/src/messages/responses/enums/cache/dictionary/index.ts
- packages/core/src/messages/responses/enums/cache/index.ts
- packages/core/src/messages/responses/enums/cache/scalar/index.ts
- packages/core/src/messages/responses/enums/cache/set/index.ts
- packages/core/src/messages/responses/enums/index.ts
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/842
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/843
this pr moves the response enums into specific folders according to the
- service they are for (ie `cache`)
- data structure (ie `dictionary`)
Also completes the migration for all dictionary apis to the new pattern
> feat: clean up response type enum folders

- examples/nodejs/access-control/package-lock.json
- examples/nodejs/access-control/package.json
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/docker/ecs-code/index.ts
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/docker/ecs-code/package-lock.json
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/docker/ecs-code/package.json
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/lambda/handler.ts
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/lambda/package-lock.json
- examples/nodejs/aws/lambda-examples/cloudwatch-metrics/lambda/package.json
- examples/nodejs/aws/lambda-examples/simple-get/lambda/simple-get/package-lock.json
- examples/nodejs/aws/lambda-examples/simple-get/lambda/simple-get/package.json
- examples/nodejs/aws/secrets-manager/package-lock.json
- examples/nodejs/aws/secrets-manager/package.json
- examples/nodejs/compression-zstd/package-lock.json
- examples/nodejs/compression-zstd/package.json
- examples/nodejs/compression/package-lock.json
- examples/nodejs/compression/package.json
- examples/nodejs/load-gen/package-lock.json
- examples/nodejs/load-gen/package.json
- examples/nodejs/observability/package-lock.json
- examples/nodejs/observability/package.json
- examples/nodejs/token-vending-machine/lambda/authorizer/package-lock.json
- examples/nodejs/token-vending-machine/lambda/authorizer/package.json
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/package-lock.json
- examples/nodejs/token-vending-machine/lambda/token-vending-machine/package.json
should fix the issue we are seeing in ci
```
Error: node_modules/@gomomento/sdk-core/dist/src/messages/responses/cache-dictionary-get-fields.d.ts(3,15): error TS1005: ',' expected.
Error: Process completed with exit code 2.
```
> fix: standardize typescript version to 4.9.5

- packages/core/src/messages/responses/enums/auth/generate-api-key.ts
- packages/core/src/messages/responses/enums/auth/generate-disposable-token.ts
- packages/core/src/messages/responses/enums/auth/index.ts
- packages/core/src/messages/responses/enums/auth/refresh-api-key.ts
- packages/core/src/messages/responses/enums/index.ts
- packages/core/src/messages/responses/generate-api-key.ts
- packages/core/src/messages/responses/generate-disposable-token.ts
- packages/core/src/messages/responses/refresh-api-key.ts
Migrates the auth responses to the new response pattern. Introduces
enums for `GenerateApiKeyResponse`, `RefreshApiKeyResponse`, and
`GenerateDisposableTokenResponse`.
> feat: migrate auth responses to new pattern

- packages/common-integration-tests/src/keys-exist.ts
- packages/core/src/messages/responses/cache-item-get-ttl.ts
- packages/core/src/messages/responses/cache-item-get-type.ts
- packages/core/src/messages/responses/cache-key-exists.ts
- packages/core/src/messages/responses/cache-keys-exist.ts
- packages/core/src/messages/responses/cache-set-if-absent-or-equal.ts
- packages/core/src/messages/responses/cache-set-if-absent.ts
- packages/core/src/messages/responses/cache-set-if-equal.ts
- packages/core/src/messages/responses/cache-set-if-not-equal.ts
- packages/core/src/messages/responses/cache-set-if-not-exists.ts
- packages/core/src/messages/responses/cache-set-if-present-and-not-equal.ts
- packages/core/src/messages/responses/cache-set-if-present.ts
- packages/core/src/messages/responses/cache-ttl-decrease.ts
- packages/core/src/messages/responses/cache-ttl-increase.ts
- packages/core/src/messages/responses/cache-ttl-update.ts
- packages/core/src/messages/responses/enums/cache/scalar/index.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/867
Also includes a bug fix in a KeysExist test (was expecting the wrong response type).
Also updates the setIf Stored/NotStored responses so they extend ResponseBase instead of BaseResponseSuccess for consistency with the update ttl responses which use Set/NotSet/Miss.
> feat: migrate item responses to new enum pattern

- packages/client-sdk-nodejs-compression-zstd/test/integration/integration-setup.ts
- packages/client-sdk-nodejs-compression/test/integration/integration-setup.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
Previoulsy we read the test cache name from the environment in CI. We
no longer do this. However a developer may have `TEST_CACHE_NAME`
set.
In that case the integration tests will always use that for the cache
name. Because of this, control tests fail since some invoke
`testCacheName()` expecting a unique cache name as opposed to a
consistent one.
Speaking with other developers, they have been hit by this gotcha. One
solution would be to change tests to specify if they expect a unique
cache name vs some cache name. That will make the tests more difficult
to maintain, so we will remove the env var instead.
> fix: remove `TEST_CACHE_NAME` env var reference in tests

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/set.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
- packages/core/src/messages/responses/cache-set-contains-element.ts
- packages/core/src/messages/responses/cache-set-contains-elements.ts
- packages/core/src/messages/responses/enums/cache/set/index.ts
Adds the `setContainsElement` command and `setContainsElements` command.
Exposes the result of a `setContainsElements` as a record from the element name to a boolean flag indicating presence/absence.
Addresses #1341
> feat: add set contains element and set contains elements

- packages/client-sdk-nodejs/test/integration/integration-setup.ts
To simplify testing against momento local, we use the momento local
credential provider when the `MOMENTO_LOCAL` environment variable
exists.
> test: support testing aganst momento local by env var presence

- examples/nodejs/cache/.eslintrc.json
- examples/nodejs/cache/basic.ts
- examples/nodejs/cache/doc-example-files/cheat-sheet-main.ts
- examples/nodejs/cache/doc-example-files/doc-examples-js-apis.ts
- packages/core/src/messages/responses/response-base.ts
This commit ports the first handful of API examples over to use
the new switch-based pattern matching style. It also updates
the API reference docs for `get` and `getBatch` to show both
the "simplified" and "pattern matching" styles of accessing
the retrieved data.
This is intended to serve as a starting point for discussion
about whether we like this approach for the docs. I built the docs
locally and looked at these examples, and I like them. If other
folks on the team are on board with this approach then we can
move forward quickly on porting the rest of the docs/examples
over.
> chore: port initial batch of example code to use `switch` style

- packages/client-sdk-nodejs/src/internal/storage-data-client.ts
- packages/client-sdk-web/src/internal/storage-data-client.ts
- packages/common-integration-tests/src/storage.ts
- packages/core/src/messages/responses/enums/store/scalar/index.ts
- packages/core/src/messages/responses/storage/scalar/storage-get.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/935
Based on written notes, I don't believe there's anything else to address in the JS storage clients, but please let me know if there are other issues.
This PR replaces `StorageGetResponse.Success` with `Found` (always returns a `StorageValue`) and `NotFound` (always returns `undefined`).
```
const getResponse = await client.get(storeName, 'key');
// quick check
console.log('what is the value?', getResponse.value()?.string());
// full switch check
switch (getResponse.type) {
case StorageGetResponse.Found:
console.log(`Got string value: ${getResponse.value().string() ?? 'not a string'}`);
console.log(`Got string value: ${getResponse.value().int() ?? 'not an int'}`);
break;
case StorageGetResponse.NotFound: { …
```
> fix: storage get response should use Found and NotFound cases

- packages/client-sdk-nodejs/src/internal/grpc/headers-interceptor.ts
Each client creates an instance of `class HeaderInterceptorProvider` which is responsible for determining whether to send the first-request headers.
To ensure each client sends them on their first request, I switched the `areOnlyOnceHeadersSent` from a `static` variable to a non-static one.
> fix: nodejs first-time headers should be sent per client

- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/src/cache-client.ts
- packages/client-sdk-web/test/integration/client-constructor-default-configs.test.ts
https://github.com/momentohq/dev-eco-issue-tracker/issues/930
> feat: add cacheclient.create function in web sdk

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-web/src/index.ts
Prior to this commit, the new response type enums are not exported
from the Web SDK, which means that the new pattern matching code
won't work. This is a blocker for finishing the docs updates.
> feat: add response type enums to exports for web sdk

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/set.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/clients/IMomentoCache.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/internal/clients/cache/momento-cache.ts
- packages/core/src/internal/utils/validators.ts
- packages/core/src/messages/responses/cache-set-length.ts
- packages/core/src/messages/responses/cache-set-pop.ts
- packages/core/src/messages/responses/enums/cache/set/index.ts
Adds missing set methods to node and web SDKs
> feat: add SetPop and SetLength

- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/core/src/internal/clients/pubsub/AbstractPubsubClient.ts
- packages/core/src/internal/clients/pubsub/IPubsubClient.ts
- packages/core/src/internal/subscription-state.ts
- packages/core/src/messages/responses/topic-subscribe.ts
This commit contains no functional changes; simply refactors the
AbstractPubSubClient to stop leaking out member variables to its
subclasses. The way it was previously defined, there were several
member variables that were required to be initialized by the child
classes, which, if you did not initialize them would result in
a runtime error instead of a compile-time error. This commit
changes the variables to be private, provides protected accessor
functions as needed, and creates a constructor function that requires
them to be passed in at initialization time. This moves any related
bugs from run time to compile time and makes it simpler to reason
about the ownership of the variables.
> chore: refactor AbstractPubSubClient to ensure safe use of required vars

- packages/client-sdk-nodejs/src/config/topic-configurations.ts
- packages/client-sdk-nodejs/src/config/transport/topics/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/topics/transport-strategy.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/core/src/internal/clients/pubsub/AbstractPubsubClient.ts
At some point in time a refactor seems to have made the TopicClient less resilient to network interruptions. It may have happened when we made changes to disable keepalives by default (due to lambda issues), or during some refactor work to add topics support to the web SDK.
This commit does the following:
* Add configuration options for grpc keepalives and enable them in the default topicclient config
* Adds a good deal of trace-level logging to help debug what is happening when subscriptions are interrupted
* Re-work the error-handling and "end of stream" logic a bit to improve connection resiliency.
I tested this on my laptop by disabling my wifi after the subscription was created. Prior to these changes, the network issues were not detected and the connection was left in a broken …
> fix: improve TopicClient connection resiliency

- examples/nodejs/cache/basic.ts
- packages/client-sdk-nodejs-compression/package-lock.json
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/sorted-set.ts
- packages/core/src/clients/ICacheClient.ts
- packages/core/src/internal/clients/cache/AbstractCacheClient.ts
- packages/core/src/internal/clients/cache/IDataClient.ts
- packages/core/src/utils/cache-call-options.ts
Currently for `sortedSetGetRank` we only support fetching in `Ascending` order.
```Typescript
await momento.sortedSetGetRank('my-cache', 'my-sorted-set', 'my-element');
```
This PR adds optional call options to `sortedSetGetRank` to sort the sorted set by `Descending` or `Ascending` order when determining the rank of the passed element.
So can call like this now:
```typescript
await momento.sortedSetGetRank('my-cache', 'my-sorted-set', 'my-element', {
order: SortedSetOrder.Descending
});
```
> feat: adds order opt to sortedset getRank

- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/storage/storage.ts
Adds a `WithStore` integration test helper to avoid leaking stores.
Previously, we leaked a store with each run of the storage tests.
> fix: stop leaking stores

- packages/client-sdk-nodejs/src/index.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/core/src/index.ts
- packages/core/src/internal/clients/pubsub/AbstractPubsubClient.ts
- packages/core/src/messages/responses/topic-discontinuity.ts
- packages/core/src/messages/responses/topic-item.ts
- packages/core/src/utils/topic-call-options.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/973
Tested new onDiscontinuity callback locally using a [stubbed topics service](https://github.com/momentohq/momento-local/pull/100) that returns only discontinuities.
> feat: add sequence number to TopicItem and add optional onDiscontinuity callback

- packages/core/src/internal/clients/pubsub/AbstractPubsubClient.ts
~~Previously, discontinuities were never shown. Increases the delay for attempting to reconnect to 5 seconds to match the go sdk, which did show discontinuities after resubscribing.~~
~~I think increasing the delay gives the server a little more breathing room to figure out that a reconnect had occurred and to send a discontinuity message to indicate the stream may have been interrupted.~~
Just increases delay for resubscribing to 500ms.
Discontinuities will be seen for network interruptions longer than the server message buffer (currently 5s).
> chore: increase topics reconnect delay to 500ms

- packages/common-integration-tests/src/cache/dictionary.ts
- packages/common-integration-tests/src/cache/sorted-set.ts
The nodejs test for `sortedSetPutElements` fails on:
```
✘ Integration tests for sorted set operations > #sortedSetPutElements > does not refresh with no refresh ttl '(2119 ms)
expected MISS but got Hit: valueArrayStringElements: 131ed5dd-b2da-4524-b635-be36df04f2b9: 42
Error: expect(received).toBeInstanceOf(expected)
```
I suspect the reason is the sleep for 1 sec is not suffiient for the test. Adding 1ms to sleep timeout to avoid this from happening.
As of 09/11/24, same error occurred for dictionary tests [(dashboard link)](https://momento.chronosphere.io/dashboards/canaries?start=1h). 
```
● Integration tests for dictionary operations › #dictionarySetField › does not refresh with no refresh ttl
expected MISS but got Hit: value2
Error: expect(received).toBeInstanceOf(expected)
``` …
> chore: add getItemTtl to sortedSetPutElement failing test

- packages/common-integration-tests/src/webhooks/webhooks.ts
The nodejs canaries failed on webhook test. It appears to be an intermittent issue. Adding log statement for debugging it more before we increase the timeout on get the webhook details.
> fix: add webhook request details log

- packages/client-sdk-nodejs/src/auth-client.ts
- packages/client-sdk-nodejs/src/preview-leaderboard-client.ts
- packages/client-sdk-nodejs/src/preview-storage-client.ts
- packages/client-sdk-nodejs/src/topic-client.ts
- packages/client-sdk-web/src/auth-client.ts
- packages/client-sdk-web/src/preview-leaderboard-client.ts
- packages/client-sdk-web/src/preview-storage-client.ts
- packages/client-sdk-web/src/topic-client.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1035
Only the CacheClient requires a config value for default TTL. All other clients have optional config options, so the entire config object can be made optional.
```typescript
const topicClient = new TopicClient();
// instead of 
const topicClient = new TopicClient({});
```
Will follow up with updates to docs/examples
> feat: optional config object for topic, auth, storage, leaderboard clients

- packages/client-sdk-nodejs/test/integration/shared/cache/replica-reads.test.ts
- packages/client-sdk-web/test/integration/shared/cache/replica-reads.test.ts
- packages/common-integration-tests/src/cache/replica-reads.ts
- packages/common-integration-tests/src/index.ts
Previously, our integration tests were written assuming consistent
reads. To avoid false positives caused by stale reads in low-latency
environments, we enforced consistent reads by setting the consistent
read header. While this reduced noise from false positives, it also
meant we lacked test coverage for replica reads and replication behavior.
To address this gap, we've added a negative test that detects
replication failures by verifying that no stale reads occur after the
expected replication delay.
The new test suite `replica-reads` implements a test that runs 10
trials in parallel. Each trial performs the following steps:
- Set: Writes a random key-value pair to the cache
- Wait: 1 second for reads to propagate
- Get: Reads the value for the key using …
> test: add negative test to detect replication failures

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/common-integration-tests/src/cache/update-ttl.ts
- Add the "NotSet" path in increase/decrease ttl apis
closes https://github.com/momentohq/client-sdk-javascript/issues/1446
> fix: add NotSet path for increase/decrease ttl apis

- packages/client-sdk-nodejs/src/errors/cache-service-error-mapper.ts
- packages/client-sdk-nodejs/test/integration/cache/large-messages.test.ts
- packages/client-sdk-web/src/errors/cache-service-error-mapper.ts
- packages/core/src/errors/errors.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/982
Removes the confusing preamble from the RESOURCE_EXHAUSTED error message. Makes more clear which limit was exceeded if that information is available in the grpc error details or `err` metadata field. 
Using the `err` metadata is preferred so that we don't rely on basic string matching if possible as error details can change any time in the future.
If all else fails, we return a generic error message: `'Limit exceeded for this account'`
> chore: clarify limit exceeded in resource exhausted errors

- packages/common-integration-tests/src/auth/auth-client.ts
- packages/common-integration-tests/src/common-int-test-utils.ts
- packages/common-integration-tests/src/topics/topic-client.ts
While investigating some canary failures, discovered that some auth topics tests were reusing topic names.
Added a new util function to ensure unique topic names are used in all topics tests.
> chore: use unique topic names in tests

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/index.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/core/src/internal/subscription-state.ts
- packages/core/src/messages/responses/topic-discontinuity.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1059
Updates the topic subscription to take the sequence page into account:
- Keeps track of last known sequence page in addition to sequence number in `SubscriptionState` so we can reconnect gracefully
- Includes sequence page detail for `TopicDiscontinuity` objects
As part of this change, had to update the client-protos dependency version as well.
Tested locally to verify both node and web clients gracefully reconnect when wifi is toggled and sequence page is used to resume from the next expected sequence number.
Also tested locally and confirmed that subscribing with an initial (arbitrary) sequence page will cause a discontinuity before getting assigned a new sequence page.
Also had forgotten to export …
> feat: support topics sequence page

- packages/client-sdk-nodejs/src/config/retry/default-eligibility-strategy.ts
- packages/client-sdk-nodejs/test/unit/config/retry/default-eligibility-strategy.test.ts
- chore: add tests for retry strategies
- feat: segregate retry decision for read and write APIs
> feat: segregate retry decision for read and write APIs

- packages/core/src/errors/errors.ts
Changing cancelled error messages. Went back and forth on the message, and made it simple to say was `cancelled` without assigning the "blame" to anyone. Although gRPC [status code](https://grpc.io/docs/guides/status-codes/) says `The operation was cancelled, typically by the caller.`
> chore: change cancelled error message to remove the word server

- LICENSE
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-nodejs/test/integration/shared/http/http-apis.test.ts
- packages/client-sdk-web/package.json
- packages/client-sdk-web/test/integration/integration-setup.ts
- packages/client-sdk-web/test/integration/shared/http/http-api.test.ts
- packages/common-integration-tests/src/http/http-apis.ts
- Add HTTP API tests to NodeJS and Web SDK for canaries. 
- Fix the copyright in LICENSE file
https://github.com/momentohq/dev-eco-issue-tracker/issues/1068
> feat: add http api tests to nodejs sdk

- packages/client-sdk-nodejs/Makefile
- packages/client-sdk-web/Makefile
To add http api tests to canaries, we use the make file base bath defined here: https://github.com/momentohq/canaries-kitchensink/blob/main/canaries/sdk-canary/index.ts#L79-L88. 
Therefore, this commit adds http-tests to makefile for both nodejs and web sdks
https://github.com/momentohq/dev-eco-issue-tracker/issues/1068
> chore: add http api tests to makefile

- packages/client-sdk-web/src/internal/client-metadata-provider.ts
This commit prevents a potential fatal runtime error caused by calling `includes()` on a variable whose value is `undefined`.
> fix: check for undefined userAgent string before calling includes()

- packages/client-sdk-nodejs/src/internal/cache-control-client.ts
- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/src/internal/internal-auth-client.ts
- packages/client-sdk-nodejs/src/internal/ping-client.ts
- packages/client-sdk-nodejs/src/internal/pubsub-client.ts
- packages/client-sdk-nodejs/src/internal/storage-control-client.ts
- packages/client-sdk-nodejs/src/internal/webhook-client.ts
- packages/client-sdk-web/src/internal/cache-data-client.ts
- packages/client-sdk-web/src/internal/pubsub-client.ts
- packages/core/src/index.ts
- packages/core/src/utils/collection-ttl.ts
- packages/core/src/utils/index.ts
- packages/core/src/utils/time.ts
Previously the code had lots of ad hoc conversion:
- deciding to use the provided ttl vs default
- converting to milliseconds by multiplying by 1000
We centralize these calculations for maintainability and to reduce
errors.
closes #1255
> chore: centralize default ttl and milliseconds conversion

- examples/fastly-compute/package.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-web/package.json
- packages/common-integration-tests/package-lock.json
- packages/common-integration-tests/package.json
Sets the package metadata repo url to the
current (github.com/momentohq/client-sdk-javascript).
Also corrects the repo url for the fastly example.
> fix: set the repo url to the current url

- .github/workflows/update-example-deps.yml
The commit attribution is wrong when we run the update-dependencies
workflow. While it should only be committing using the bot account, an
individual developer is also tagged on the commit. This is incorrect.
The create-pull-request GitHub action fixed the attribution for the
commits in v6. We upgrade to v7 for the latest.
> fix: upgrade to open pull request v7 for correct attribution

- .github/workflows/build.yml
Addresses https://github.com/momentohq/dev-eco-issue-tracker/issues/1096
For PR checks that need an auth token to run successfully, we first check that the github actor that triggered the workflow has write permissions to the repo before sharing the secrets and running the tests.
This should allow us the ability to approve workflows on PRs that come in via forked branches, making it easier to accept open-source contributions.
**Intended behavior**
1. PR from fork comes in, requires workflow approval from a maintainer
2. Maintainer approves, starts workflow, becomes the "triggering actor"
3. GitHub Actions workflow checks triggering actor's permissions, proceeds if they have at least "write" access to the repo
4. PR checks run with access to secrets due to usage of `on: …
> ci: check permissions of triggering actor before running PR checks

- packages/client-sdk-nodejs/src/internal/grpc/grpc-channel-options.ts
The current default Node.js message size limits are 5MiB for inbound
and outbound messages. Because the service limits may be slightly higher
for certain customers, we double the limits to provide a nice tradeoff
between user experience (not having to override the limits),
performance, and protective guardrails.
> chore: bump client message size limits

- packages/client-sdk-nodejs/src/config/configuration.ts
- packages/client-sdk-nodejs/src/config/leaderboard-configuration.ts
- packages/client-sdk-nodejs/src/config/storage-configuration.ts
- packages/client-sdk-nodejs/src/config/topic-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/cache/transport-strategy.ts
- packages/client-sdk-nodejs/src/config/transport/storage/transport-strategy.ts
- packages/client-sdk-nodejs/src/config/transport/topics/transport-strategy.ts
- packages/client-sdk-web/src/config/configuration.ts
- packages/client-sdk-web/src/config/leaderboard-configuration.ts
- packages/client-sdk-web/src/config/topic-configuration.ts
- packages/client-sdk-web/src/config/transport/transport-strategy.ts
In order to make our config copy constructors maintainable and less
error-prone, we should use the spread operator over `this`.
Previously in the copy constuctors we built a copy of the
corresponding properties by hand. Because some properties are
optional, and because we add new properties over time, we introduced
drift between the new properties and various copy constructors.
That is, when we added new properties, some copy constructors were out
of date and hence falling back to defaults instead of copying those
new properties over.
From the cache static transport strategy:
```typescript
withNumClients(numClients: number): GrpcConfiguration {
return new StaticGrpcConfiguration({
deadlineMillis: this.deadlineMillis,
maxSessionMemoryMb: this.maxSessionMemoryMb,
numClients: numClients,
}); …
```
> fix: copy constructors should use spread operator

- .github/workflows/build.yml
CI was checkout out the main branch on PR checks instead of the merge commit (fixes same bug as https://github.com/momentohq/client-sdk-rust/pull/435)
> ci: ensure we checkout the correct commit on pr checks

- packages/client-sdk-nodejs/test/integration/test-retry-metrics-collector.ts
- packages/client-sdk-nodejs/test/unit/test-retry-metrics-collector.test.ts
- Add a retry test metrics collector class that allows us to collect data regarding no of retries, total number of retries and average time between the retries. 
https://github.com/momentohq/dev-eco-issue-tracker/issues/1091
> feat: add retry test metrics collector

- packages/client-sdk-nodejs/src/config/transport/cache/grpc-configuration.ts
- packages/client-sdk-nodejs/src/config/transport/cache/transport-strategy.ts
Adds `GrpcConfiguration` copy constructors to set the max send/receive
message length.
> chore: add copy constructors for max send/recieve message length

- packages/client-sdk-nodejs/src/config/configuration.ts
Add a convenience setter for the max message length on the Node.js
cache client config.
> chore: add max message length convienence setter on client config

- .github/workflows/build.yml
It appears that sometimes the `merge_commit_sha` we want to check out in combination with using `on: pull_request_target` does not always exist.
This PR ensures we checkout `merge_commit_sha || pull_request.head.sha` so that it has a fallback ref that will always exist. (The head.sha is the last commit on the PR, the merge_commit_sha is the test merge with main).
Note: The updated workflow will not run on this PR because `pull_request_target` runs in the context of the base branch (main), not the PR branch.
> ci: checkout default ref on PRs if merge commit is unavailable

- packages/client-sdk-nodejs/src/config/configuration.ts
- packages/client-sdk-nodejs/src/config/transport/cache/grpc-configuration.ts
Previously we did not indicate that max message length was in
bytes. We adjust that here.
> chore: document max message length units

- .github/workflows/build.yml
In the following pull request: [#1505](https://github.com/momentohq/client-sdk-javascript/pull/1505), it was observed that the CI process consistently builds against the previous commit instead of the head commit. 
You can verify this by reviewing the "Setup repo" step under the "Check Ref logs" section in CI Actions, which indicates the commit being tested.
To address this issue, this update ensures that the CI always tests against the pull request's head SHA rather than the merge commit SHA, improving accuracy and reliability in the testing process.
> chore: use the pull request head sha to build the ci

- packages/client-sdk-nodejs-compression-zstd/package-lock.json
- packages/client-sdk-nodejs-compression-zstd/package.json
- packages/client-sdk-nodejs-compression-zstd/test/integration/compression.test.ts
Bumps the zstd version in the zstd compression library to 2.0.0. Though this version maintains API compatibility with version 1.0, the binary may be slightly different. Hence we update the tests. Additionally, version 2.0 does not throw an error when data is compressed but the frame header is invalid. Instead it returns a 0-length byte array. We remove that test.
> chore: bump zstd version

- packages/common-integration-tests/src/cache/dictionary.ts
- packages/common-integration-tests/src/cache/sorted-set.ts
- packages/common-integration-tests/src/webhooks/webhooks.ts
- Removing logs from tests that were added to debug the canaries. Since now we use consistent reads inside canaries, we can get rid of the logs that were added.
> chore: remove logs from tests

- packages/client-sdk-nodejs/test/integration/retry/automated-retry-tests.test.ts
- packages/client-sdk-nodejs/test/momento-rpc-method.ts
- packages/client-sdk-nodejs/test/unit/momento-rpc-method.test.ts
- Add more retry tests for RPCDelayer
- Add a MomentoRPCMethodConverter class that helps convert the MomentoRPCMethod enum to its corresponding metadata type that momento local can parse. 
- Added unit test for MomentoRPCMethodConverter class
https://github.com/momentohq/dev-eco-issue-tracker/issues/1109
> feat: add retry tests for RpcDelayer

- examples/nodejs/topics/package.json
- examples/nodejs/topics/topic-refresh-token.ts
- Adds an example demonstrating how to use the Node.js SDK to generate disposable tokens for topics. The example includes functionality to refresh the client before the token expires.
https://github.com/momentohq/dev-eco-issue-tracker/issues/1129
> chore: add topic token refresh client example

- packages/client-sdk-nodejs/src/internal/grpc/grpc-channel-options.ts
- Adds a flag to disable the dynamic DNS service config
- Enabled gRPC logging with `GRPC_VERBOSITY=DEBUG GRPC_TRACE=all npm run example`, but couldn't reproduce the `ENODATA` error.  
- Tried spoofing a TXT record using `/etc/hosts`, but it only supports IP address mappings, not TXT records.  
- Used `tcpdump` to capture DNS queries:  
```sh
sudo tcpdump -i any -vvv port 53 | grep -i cache.cell-alpha-dev.preprod.a.momentohq.com
```  
- Without the SDK flag, observed TXT record lookups.  
- With the `grpc-service-config-flag` enabled (as in the recent commit), no TXT lookups occurred.  
This confirmed that enabling the flag prevents unnecessary TXT record lookups and avoids the `ENODATA` error.
<details>
<summary>Click to expand</summary>
```sh
tcpdump: data link type PKTAP
tcpdump: …
```
> fix: disable dynamic DNS service config

- .github/workflows/build.yml
- .vscode/client-sdk-javascript.code-workspace
- examples/nodejs/aws/lambda-examples/advanced-compression/package-lock.json
- examples/nodejs/aws/lambda-examples/advanced-compression/package.json
- examples/nodejs/aws/lambda-examples/advanced-compression/postbuild.ts
The current version of `@mongodb-js/zstd` has a deficiency loading the
native node module as compared to the previous major version. The
loader needs fallbacks to
`@mongodb/zstd/build/{Release,Debug}/zstd.node` to fully work when
bundling for lambda. We will open an issue with mongo about this.
In the interim we add a postinstall step to copy the file in the
`Debug` directory so the build will pass.
We also provide scripts to build and package for aws `npm run rebuild:aws` and dev `npm run rebuild:dev`.
> fix: aws lambda zstd example needs postinstall step

- examples/nodejs/aws/lambda-examples/advanced-compression/esbuild.ts
- examples/nodejs/aws/lambda-examples/advanced-compression/package-lock.json
- examples/nodejs/aws/lambda-examples/advanced-compression/package.json
- Removes `postInstall` script from `package.json`
- Updates the `nativeNodeModulesPlugin` in esbuild to force resolve path
- Add plugin to esbuild config
> fix: force resolve to release path in nativeNodeModulesPlugina and include that in esbuild config

- .github/workflows/retry-tests.yml
- packages/client-sdk-nodejs/test/integration/integration-setup.ts
- packages/client-sdk-nodejs/test/integration/retry/topic-client-retry.test.ts
- Add keep-alive tests for test-admin:  
- Introduce `TestAdminClient` in `integration-setup` to handle port blocking/unblocking.  
- Test flow:  
1. Start a subscription and verify heartbeats.  
2. Block the admin port and confirm heartbeats stop.  
3. Unblock the port and ensure heartbeats resume.
closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1186
> feat: add test-admin keepAlive tests

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/src/config/middleware/cache-request-logging.ts
- packages/client-sdk-nodejs/src/config/retry/momento-rpc-method.ts
- packages/client-sdk-nodejs/src/internal/leaderboard-data-client.ts
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
- packages/client-sdk-web/src/internal/leaderboard-data-client.ts
Bumps the generated-types dependency on the nodejs sdk to the latest
version (v `1.24.0`).
> chore: bump generated-types on nodejs

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
Bumps the generated types dependency to the latest version, which also
bumps grpc-js to v1.13.1. We also bump the grpc-js dependency to match
that.
> chore(nodejs): bump generated types and grpc-js to latest version

- packages/client-sdk-nodejs/src/internal/grpc/grpc-client-wrapper.ts
- packages/client-sdk-nodejs/src/internal/grpc/idle-grpc-client-wrapper.ts
- packages/client-sdk-nodejs/test/unit/grpc/idle-grpc-client-wrapper.test.ts
- Adds logic to inspect the gRPC channel’s ConnectivityState via client.getChannel().getConnectivityState(true).
- If the client’s channel is in TRANSIENT_FAILURE or SHUTDOWN state, the wrapper will now:
- Log the reason
- Close the existing client
- Create a new client via the provided factory
- This is in addition to existing logic that rotates the client based on:
- Idle timeout (maxIdleMillis)
- Maximum client age (maxClientAgeMillis)
- Added unit tests for the wrapper class
work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1197
> feat: grpc channel state detection and auto-reconnect

- packages/client-sdk-nodejs-compression-zstd/package-lock.json
- packages/client-sdk-nodejs-compression-zstd/package.json
- packages/client-sdk-nodejs-compression/package-lock.json
- packages/client-sdk-nodejs-compression/package.json
Previously the compression and compression-zstd libraries depended
directly on generated types. This is not necessary since they depend
on the nodejs SDK, which in turn depends on generated types.
This introduced the possibility of the generated types in the
compression (zstd) libraries having conflicting versions.
> fix: compression libraries don't need to depend on generated-types

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
Bumps the generated types dependency to the latest version (1.24.2)
which removed extraneous production dependencies.
> chore: bump generated types

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
Updates the generated types dependencies to 0.124.3 where grpc is a peer dependency. This should resolve deduplication failures our users have seen when they install their own version of grpc.
> chore: bump generated types to 0.124.3

- packages/client-sdk-nodejs/package-lock.json
- packages/client-sdk-nodejs/package.json
- packages/client-sdk-web/package-lock.json
- packages/client-sdk-web/package.json
Similar to #1545, we update the generated types but this time with protobuf as a peer dependency. This protects application developers from the same dual package hazard we saw with grpc.
> chore: bump generated types to 0.124.4

- packages/client-sdk-nodejs/src/internal/grpc/retry-interceptor.ts
- packages/client-sdk-nodejs/test/integration/retry/fixed-timeout-retry-strategy.test.ts
Closes https://github.com/momentohq/dev-eco-issue-tracker/issues/1206
Assigns the Min(retry deadline, overall deadline) on each retry attempt to ensure we don't exceed the client's overall deadline.
Turns out that like the Java retry interceptor, the JS retry interceptor needs to manually check whether the current time exceeds the overall deadline. Otherwise, a timeout error is never returned. The status code on retry attempts do not change to DEADLINE_EXCEEDED if a retry attempt's deadline was exceeded; it remains the original status code and trying to change it will cause an UNKNOWN error.
> fix: make sure retry deadline does not exceed overall deadline

- packages/client-sdk-nodejs/src/config/retry/fixed-timeout-retry-strategy.ts
- packages/client-sdk-nodejs/src/config/retry/retry-strategy.ts
- packages/client-sdk-nodejs/src/internal/grpc/retry-interceptor.ts
- packages/client-sdk-nodejs/src/internal/utils.ts
- packages/client-sdk-nodejs/test/integration/retry/exponential-backoff-retry-strategy.test.ts
- packages/client-sdk-nodejs/test/integration/retry/fixed-timeout-retry-strategy.test.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1214 
The JS fixed timeout retry strategy was overwriting the grpc deadline from the initial request when it should update the deadline only after the initial request fails. Once the initial request fails, the retry deadline (responseDataReceivedTimeoutMillis) should be used.
Updates the tests to ensure this logic is exercised.
> fix: fixed timeout retry strategy should overwrite deadline only after first request fails

- packages/core/src/messages/responses/cache-set-if-absent-or-hash-not-equal.ts
I fixed the import for CacheSetIfAbsentOrHashNotEqualResponse which caused errors when used in examples.
> fix: fixed import in setIfAbsentorHashNotEqual response type

- packages/client-sdk-nodejs/test/integration/cache/abort-signal.test.ts
In low latency environments, like in our canaries, these tests can become flaky when the get/set commands complete before the AbortSignal can be processed.
This PR updates the tests so that each one runs 3 times and it expects at least one to pass. This should hopefully make canary alerts less noisy.
> fix: make AbortSignal tests less flaky

- packages/client-sdk-nodejs/src/internal/cache-data-client.ts
- packages/client-sdk-nodejs/test/integration/cache/abort-signal.test.ts
- packages/core/src/utils/cache-call-options.ts
For clarity rename the signal property to cancel and RPC from `signal`
to `abortSignal`.
> refactor: rename `signal` cancellation property to `abortSignal`

- packages/client-sdk-nodejs/test/integration/cache/abort-signal.test.ts
commenting out the flaky `get` abortSignal tests for now to avoid noisy alerts
also undid the "ci-only" changes since they didn't fix the issue
made a ticket to address this issue more permanently next week
> chore: comment out flaky abortSignal tests

- packages/client-sdk-nodejs/package.json
- packages/client-sdk-nodejs/test/integration/cache/abort-signal.test.ts
- packages/client-sdk-nodejs/test/integration/cache/large-messages.test.ts
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1257
Re-enables the flakey `get` AbortSignal tests and configures those tests to run in CI, but not in canaries, by adding the `testPathIgnorePatterns` filter to the `npm run integration-test-cache` command that the canaries use.
Using `ItOnlyInCi` did not impact the canaries, only affected whether the tests would run in GitHub Actions CI workflows. Upon auditing that usage, I also updated the large messages test. That test should be run only in CI, not locally where it will fail unless dev account has correct limits.
> chore: exclude AbortSignal tests from canary npm target
